### ISSUE TITLE
program was stuck in broker.Connect() when using rabbitmq

### ISSUE THREAD

**Issue by panjf2000** [micro/go-plugins#105]
```
rb := rabbitmq.NewBroker(broker.Addrs(config.RabbitMQConf[config.ENV]...), rabbitmq.Exchange("xxx"))
if err := rb.Connect(); err != nil {
		log.Fatalf("Broker Connect error: %v", err)
	}
```
i was using the rabbitmq broker in my project and it was stuck in broker.Connect().
so, is there any wrong step in my codes?why can't it connect to rabbitmq?

**Comment by asim** [comment]
It's likely because it cannot connect to the address you are specifying

**Comment by asim** [comment]
Please specify an amqp url of the format "amqp://guest:guest@127.0.0.1:5672" and close the issue if this has resolved the problem.
