### ISSUE TITLE
Noop registry

### ISSUE THREAD

**Issue by sysradium** [micro/go-plugins#107]
Is there a reason for not having a compatible`NewRegistry` function signature and a defined `init()` 
 for the `noop` registry?

Because sometimes I find it quite useful to be able to disable the registry at all. Currently it requires me to write an ugly wrapper:

```go
	cmd.DefaultRegistries["noop"] = func(opts ...registry.Option) registry.Registry {
		return noop.NewRegistry()
	}
``` 

It is an easy fix, but maybe there is a valid justification

**Comment by asim** [comment]
Done https://github.com/micro/go-plugins/commit/ef492a10de01121b0b2235c5411d90a8f2894522
