### ISSUE TITLE
Grpc error code is always 500

### ISSUE THREAD

**Issue by sysradium** [micro/go-plugins#110]
If I use `errors` package from go-micro it always returns the 500 grpc error, regardless of what code I set.

Created a PR which explains my issue and a possible solution https://github.com/micro/go-plugins/pull/109

It looks like you expect developers to use `grpc.Errof` from `utils.go` which creates `rpcError`, however this means that the code is tied to grpc transport.

**Comment by asim** [comment]
The reason its done like this is because it's supposed to interoperate with grpc services which would expect a valid grpc error.

**Comment by sysradium** [comment]
This does not answer my question. If I use `errors` from go-micro package I will NOT get the correct grpc error. I will always get `500` regardless of what error I return from a handler.

It's because `grpc` plugin only sets the correct grpc code if you return `rpcError` from your handler. However this kills the idea of `micro` being transport agnostic. I expected that plugin to work with the `errors` package from `go-micro`. It does look too hard to implement. Still thing it should be `rpcError`?

**Comment by asim** [comment]
Can you clarify the flow here and what you expect the end result to be? Are you expecting the go-micro grpc based service to return a micro error or a grpc error? Are you expecting the server to do this conversion or the client? Do you expect this to work with the standard grpc protocol? Do you expect error codes to be of grpc numeration or something else?

**Comment by sysradium** [comment]
The flow is this:
1. I write proto files
2. I Implement the services based on these proto files
3. I use package https://github.com/micro/go-micro/tree/master/errors to return any error from my handlers

What happens is that if I use `grpc` it converts these codes to `grpc` default codes. If switch to `http` it uses `http` codes.

In current situation in order to get native `grpc` status code I am forced to use this https://github.com/micro/go-plugins/blob/master/server/grpc/util.go#L228, because it returns  error of type `rpcError` which is then picked up by `grpc` server plugin, which converts them to native errors.  But this forces me to stick to `grpc` protocol. I want to stay flexible.

**Comment by bkono** [comment]
I personally reached for the grpc codes, because they have significantly more specificity by default. It seems reasonable if someone wants to stick with the smaller set provided by micro errors to allow for transport agnostic error code, you could implement a simple mapping in the spirit of convertCode. I'd do it more along these lines ... https://github.com/sysradium/go-plugins/pull/1.

Few things to be aware of with doing it though, the expected HTTP to gRPC mapping actually isn't what most people would expect by default. To get things to line up, you'd be deviating a bit from this: [http-grpc-status-mapping](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md)

**Comment by sysradium** [comment]
@bkono well yeah, that's what I want. It should be probably a separate function with well defined mapping, not inlined as in my case. But it the plugin should use `microErrors.Error` not some invented `rpcError` :)

**Comment by asim** [comment]
https://github.com/micro/go-plugins/commit/c73752af24f66b14eb1fc1eaf3427c9fdc87a4f6

**Comment by asim** [comment]
https://github.com/micro/go-plugins/commit/2aed829932cc858b85d67ad33fab34ccfedb558a

**Comment by asim** [comment]
Parsing errors client and server side. If satisfied please close the issue.

**Comment by sysradium** [comment]
@asim awesome, thank you. Will look at that tomorrow.
When are you going to release this as a part of 0.2.2?

**Comment by asim** [comment]
When you look at it and close the issue.

**Comment by asim** [comment]
Also it will be a 0.3.0 since there's other feature changes.

**Comment by sysradium** [comment]
Looks ok, thank you. Will open another issue in case of problems.
