### ISSUE TITLE
mesage queue broker that replaces kafka: https://github.com/ninibe/netlog

### ISSUE THREAD

**Issue by joeblew99** [micro/go-plugins#12]
This looks really nice. I have not used it yet.
Its a 100% golang replacement for Kafka, and so has the advantage of clean deployment and no JVM heap to contend with.
Its os also a 100% http based API, which although is going to have lower perf for sure, is nice for ease of use.

**Comment by asim** [comment]
It's a 3 week old project so a bit early to say what will happen. I probably don't want to include this in the official go-plugins repo until there's actually a stable client interface. Given the experience with kubernetes and how often changes would cause breaking builds I have a feeling with a 3 week old project it will be quite similar.

If you would like to implement the plugin I can feature your implementation a "Community Contribution" in the readme and link to it.

**Comment by joeblew99** [comment]
well before all the implementation aspects, the right question is "Is this appropriate for go-micro".
Security is orthogonal and so i think its really a good fit for go-micro, because then when writing a service i can leverage it.

It sounds like your agree.

But i relation to me implementing it, i dont have time. Project pressures as always.
I was more just wanting to open up the idea, so that others can see a way forward

**Comment by asim** [comment]
Something at this early a stage is probably not appropriate in the official repo. If you want to ask for someone else to implement it, join the Slack and start a discussion with the community.

**Comment by joeblew99** [comment]
ok
