### ISSUE TITLE
Issue while trying to use googlepubsub as broker in go micro

### ISSUE THREAD

**Issue by Nishant967** [micro/go-plugins#124]
Currently i am using nats as broker for my go micro based application. But now i want to move it to googlepubsub. While moving it to pubsub I am facing the issue mentioned below:

**Error Message**
# github.com/micro/go-plugins/broker/googlepubsub
../../../micro/go-plugins/broker/googlepubsub/googlepubsub.go:46: s.sub.Pull undefined (type *"cloud.google.com/go/pubsub".Subscription has no field or method Pull)
../../../micro/go-plugins/broker/googlepubsub/googlepubsub.go:105: p.pm.Done undefined (type *"cloud.google.com/go/pubsub".Message has no field or method Done, but does have "cloud.google.com/go/pubsub".done)
../../../micro/go-plugins/broker/googlepubsub/googlepubsub.go:162: assignment count mismatch: 2 = 1
../../../micro/go-plugins/broker/googlepubsub/googlepubsub.go:186: too many arguments in call to b.client.CreateSubscription
	have ("golang.org/x/net/context".Context, string, *"cloud.google.com/go/pubsub".Topic, time.Duration, nil)
	want ("golang.org/x/net/context".Context, string, "cloud.google.com/go/pubsub".SubscriptionConfig)

**Error Message End**

Below is my code in which i just tried to start broker nothing else.

**Code**

package main

import (
	"log"
	_"github.com/micro/go-micro/broker"
	_"github.com/micro/go-micro/cmd"
	"github.com/micro/go-plugins/broker/googlepubsub"
	"github.com/micro/go-micro/cmd"
)

func main() {
	cmd.Init()
	log.Println("Google pubsub")
	// broker := googlepubsub.NewBroker()
        log.Println(broker.String())

	if err := broker.Init(); err != nil {
		log.Fatalf("Broker Init error: %v", err)
	}

	if err := broker.Connect(); err != nil {
		log.Fatalf("Broker Connect error: %v", err)
	}

}

**Code Ends**

If possible please recommend any guide on using google pubsub broker with go micro

**Thanks**

**Comment by asim** [comment]
The error is indicating to you that there's a mismatch between the libraries you're using. Basically you have stale code. Update your go-plugins repository and its dependencies. The best way to do this is by running `go get -u ./...` on your code base

**Comment by Nishant967** [comment]
Thanks asim for the reply!!!
I have one more question regarding google pubsub broker.
The implementation is same as other brokers like nats or any other broker?

**Comment by asim** [comment]
Yes. Its a broker plugin like all others. If you look at the package you'll see it returns a broker interface https://github.com/micro/go-plugins/blob/master/broker/googlepubsub/googlepubsub.go#L214. Initialisation requires passing a google project id or client. 

Closing issue since we've moved on from the original topic.

**Comment by Nishant967** [comment]
One more question
Is it possible to subscribe message in batches from queue using pubsub micro?

**Comment by asim** [comment]
I would advise you to look at the implementation. It's only 200 lines of code. Also note that the broker interface does not provide any sort of batch interface. Each message is processed individually by the handler provided.
