### ISSUE TITLE
question: authentication and authourisation a good idea ?

### ISSUE THREAD

**Issue by joeblew99** [micro/go-plugins#13]
https://github.com/ory-am/hydra

Basically go-micro provides lots of the boiler plate, which i love.
But i have not seen anything about the plugable authentication / authourisation.
I dont want to be dependent on S3, and would like to see a thing like hydra supported in go-micro.

What do others thing though ?

**Comment by asim** [comment]
Auth is being addressed in the go-platform https://github.com/micro/go-platform.

**Comment by joeblew99** [comment]
so its designed to be plugable ? But not at the go-micro level, but more internally where a developer is buildings their own code ?

**Comment by asim** [comment]
Authentication is not a core concern for microservices therefor its not built directly into go-micro as an interface. The higher level concerns are addressed at the go-platform level. Auth is an interface like any other and a plugin can be implemented for it.

**Comment by joeblew99** [comment]
ok got it thanks.

I will probably start to use go-micro. I have a project thats getting too much boiler plate and go-micro will really be a huge help.
Any advice about production readyness ?

**Comment by asim** [comment]
There's a few companies already using go-micro, either in production or going to production soon. It's still an early stage project being battle tested so there may be issues or tweaks required but the experience so far has been positive.

**Comment by joeblew99** [comment]
ok thanks !!
