### ISSUE TITLE
Provide ability to modify GRPC Max Message Size

### ISSUE THREAD

**Issue by shomali11** [micro/go-plugins#132]
GRPC has an Option to allow to modify the Max Message Size. It is currently defaulted at 4MB.

```
const (
	defaultClientMaxReceiveMessageSize = 1024 * 1024 * 4
	defaultClientMaxSendMessageSize    = math.MaxInt32
)

...

// WithMaxMsgSize returns a DialOption which sets the maximum message size the client can receive. Deprecated: use WithDefaultCallOptions(MaxCallRecvMsgSize(s)) instead.
func WithMaxMsgSize(s int) DialOption {
	return WithDefaultCallOptions(MaxCallRecvMsgSize(s))
}

```

The GRPC Plugin (under go-plugins) should have the ability to allow the user to pass a new Max Message Size limit (and internally micro would set the new limit using GRPC's Options)

**Comment by asim** [comment]
Could you maybe provide a PR that does this?

**Comment by asim** [comment]
No response, closing
