### ISSUE TITLE
Resurrect Kubernetes registry

### ISSUE THREAD

**Issue by asim** [micro/go-plugins#14]
Resurrect the kubernetes registry https://github.com/micro/go-plugins/tree/k8s/registry/kubernetes and make it use a versioned version of the client so we don't suffer from breaking changes.

Also make it store endpoint metadata so we maintain that information.

**Comment by nickjackson** [comment]
I'm writing something that talks directly with the http API. It didn't seem worth using the client until something like this happens. https://github.com/kubernetes/kubernetes/issues/5660.

Working on metadata as we speak. 

Not sure how to write tests for it yet.

**Comment by asim** [comment]
The REST api seems pretty straightforward so yea that will actually work quite well as long as we say its supporting a certain version like 1.2. The last I looked I was thinking maybe to store service info in the service annotations and then node info against each node. Not yet sure how feasible it is. Its sort of painful to annotate things that kubernetes launches and it would be even worse putting it somewhere that wouldn't get cleaned up. If nodes died. We're already having to reap nodes in Consul because the TTL doesn't actually expire anything.

Appreciate you chiming in and look forward to seeing what you come up with. On the testing front. Mock the API responses expected and just run the client against that.

**Comment by nickjackson** [comment]
Yeah, looking at storing metadata as annotations on the pods, as that way you won't have to worry about the cleanup.

Setting the metadata should be quite simple, as the pod ID can be made available inside the pod as an env var. Once you have that ID, you can set the annotations using the api, which can be done in `Register()`

Getting the metadata back out is a bit fiddly, as it will have to zip two k8s responses together but not too bad.

**Comment by asim** [comment]
Sounds like you've got a good handle on it. I think a working implementation is the first thing, we can worry about optimisations later. Could be that the Watcher is implemented and people can use that if they want something more efficient,  or embed in go-platform/discovery which does the caching for you via the Watcher. 

Also remember services can be run in Headless move which will actually return all the ips of the pods so we can really do client side load balancing with go-micro rather than offloading to kube-proxy. Choice is left to the user obviously.

**Comment by nickjackson** [comment]
I'm grabbing all the nodes & ports using the k8s `endpoints` api, so I'm actually ignoring the Service clusterIP altogether. Thought giving micro the control would be better as it would allow for more advanced selectors.

**Comment by nickjackson** [comment]
However, as you said I'm sure that could be an option.

**Comment by asim** [comment]
Ah ok interesting. Wasn't sure whether `endpoints` returned all the info about nodes.

**Comment by nickjackson** [comment]
Returns the ips and ports of the pods, but not the annotations.

**Comment by asim** [comment]
Ah ok, hence the two calls. Alright I'll leave you to it.

**Comment by nickjackson** [comment]
Will hopefully have something tomorrow.

**Comment by nickjackson** [comment]
@asim is there much difference in `GetService` returning a list of services with a single nodes, or one service with several nodes?

**Comment by asim** [comment]
The returned list `[]*registry.Service` is a list of service nodes grouped by Name/Version. It's better to maintain consistency with all the other implementations and return it in the same form.

**Comment by asim** [comment]
https://github.com/micro/go-plugins/pull/18
