### ISSUE TITLE
kafka: cannot subscribe to several topics

### ISSUE THREAD

**Issue by alexppxela** [micro/go-plugins#145]
Hi,

There is an error when I try to register to several kafka topics.
The code is
```golang
service := micro.NewService(
	micro.Name(ServiceName),
	micro.Broker(kafka.NewBroker(func(o *broker.Options) { o.Addrs = brokerURLs })),
)
service.Init()

handler := &MyHandler{}
notification.RegisterNotificationHandler(service.Server(), handler)

if err := micro.RegisterSubscriber(aTopic, service.Server(), handler.aEvent); err != nil {
	log.Fatalf("Cannot register subscriber %s : %s", aTopic, err)
}
if err := micro.RegisterSubscriber(bTopic, service.Server(), handler.bEvent); err != nil {
	log.Fatalf("Cannot register subscriber %s : %s", bTopic, err)
}
```

The second call to `RegisterSubscriber` produces this error: `cluster: client is already used by another consumer`.
Is there a way to subscribe to several kafka topics?

**Comment by asim** [comment]
We use sarama under the covers. It looks like the client does not allow more than one consumer. I will need to rewrite this to create a new client before creating the consumer. Feel free to PR if you have time.

**Comment by asim** [comment]
This issue should be resolved with this commit https://github.com/micro/go-plugins/commit/32b2bf85c77298d0b0cde720dc30bdacf8820de0. We now create a new client per consumer on subscribe. 

Please let me know if the fix works and then close the issue. Thanks.

**Comment by alexppxela** [comment]
Thanks, I've done a similar change but I didn't test it before sending a PR.
Thanks a lot

**Comment by alexppxela** [comment]
Re,

It works in my tests. But there is a crash if `Disconnect` is called.
`k.sc` is not initiliazed anymore.
If we do not want to keep it, we can delete it from struct or keep all clients in a map as in https://github.com/alexppxela/go-plugins/commit/b23777ec5739b02d5eea3b5d7fcc8df5b630eb9f

**Comment by asim** [comment]
Sure feel free to PR the fix so we keep a map of clients and disconnect them.
