### ISSUE TITLE
How to set the default Registry and Broker When I Publish a message with the NATS broker（Micro on kubernetes）?

### ISSUE THREAD

**Issue by Aavon** [micro/go-plugins#149]
```
_DEF_CLIENT "github.com/micro/go-micro/client"
```

```
pub := _DEF_CLIENT.NewPublication(MAIL_TOPIC_NAME,&_DEFINE.SendReqMail{
        Tos: tos,
        ....
    })
    err = _DEF_CLIENT.Publish(ctx,pub)
```

but I get the follow logs:
```
2018/02/07 09:53:18 Broker Listening on [::]:35082
2018/02/07 09:53:18 consul.watch: Watch (type: services) errored: Get http://127.0.0.1:8500/v1/catalog/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused, retry in 5s
```
It seems like the client use consul(default) to find the endpoint or service,but I have set the default client:

```
// create registry and selector
	r := kubernetes.NewRegistry()

	s := cache.NewSelector(
		selector.Registry(r),
	)

	//Client
	client.DefaultClient = gcli.NewClient(
		client.Registry(r),
		client.Selector(s),
	)

	//Server
	server.DefaultServer = gsrv.NewServer()
```

I tried create a new broker
```
pub := nat.NewBroker(...)
..
pub.Publish(...)
```
it works well

-----------
I log in:github.com/micro/go-plugins/client/grpc/grpc.go:434
```
        fmt.Println("BROKER",g.opts.Broker.String())
	fmt.Println("BROKER",g.opts.Broker.Address())
	fmt.Println("BROKER",g.opts.Broker.Options())
	g.once.Do(func() {
		g.opts.Broker.Connect()
	})
```

```
BROKER http
BROKER :0
BROKER {[] false json &lt;nil&gt; context.TODO}
```
It is not nats...

###And I find 

**In grpc Client**

```
func (g *grpcClient) Publish(ctx context.Context, p client.Publication, opts ...client.PublishOption) error
```

**In client interface**

```
// Publishes a publication using the default client. Using the underlying broker
// set within the options.
func Publish(ctx context.Context, p Publication) error 
```
So I and NATS broker  in micro.Option and start wit --broker=nats 

But them do not works...

Looking forward to your reply！

**Comment by asim** [comment]
It looks as though you're using micro in a very strange way. 

If you're using the default client then do

```
defaultClient.Init(client.Broker(nats))
```

If you're creating a new service 

```
service := micro.NewService(
        micro.Broker(nats),
)
```

If you're using the toolkit

```
import _ "github.com/micro/go-plugins/broker/nats"
```

And then use the flag
```
service --broker=nats
```

**Comment by Aavon** [comment]
It is somewhat confusing.
Simply,I use the broker in a service. In a handle function,such as SendMail.I need to pubulish the message the specialized MAIL Service.
I did:

```
service := micro.NewService(
        micro.Broker(nats),
)

import _ "github.com/micro/go-plugins/broker/nats"

service --broker=nats

```
（_DEF_CLIENT "github.com/micro/go-micro/client"）
But when I use _DEF_CLIENT.Publish(),it use the default httpBroker..

**Comment by asim** [comment]
If you are specifying `micro.Broker` as an option to `micro.NewService` then you should not using command line flags. 

Either do this

## Option

```
import "github.com/micro/go-plugins/broker/nats"

nb := nats.NewBroker()

// pass nats as broker option
service := micro.NewService(
        micro.Broker(nb),
)
```

OR

## Flag

```
import _ "github.com/micro/go-plugins/broker/nats"

service := micro.NewService()
// initialise command line
service.Init()
```

```
// invoke as flag
service --broker=nats
```

Usage wise, do not use the default client. Use your service client `service.Client()`. This has been initialised based on the above examples.

**Comment by Aavon** [comment]
I may understand.

**In the Subscriber**

-----------

code is like this:
```
    server  := service.Server()
    sub := server.NewSubscriber(topic,SubHandler)
    err  = server.Subscribe(sub)
```
**So it works.**


**In the Publisher**

-------------
Before, I want to use the default broker as a global setting, but it not work....
according to your advice，I use the broker directly to publish. Using the service.Client is a little
inconvenient.
---------------------

Thanks.
