### ISSUE TITLE
GRPC client/server

### ISSUE THREAD

**Issue by asim** [micro/go-plugins#15]
Create a GRPC plugin so we can talk to grpc applications using go-micro. GRPC is actually a protocol as well as an RPC framework. It maybe possible to create a codec which can speak the protocol. Alternatively it may be easier to create a client/server.

**Comment by asim** [comment]
Been thinking about this a bit. Actually started writing something then basically trashed the folder. I think if we can get this write, it could be written into go-micro itself rather than in go-plugins. It would really add something very powerful for Micro and the gRPC community. Cross collaboration and use of Micro features would be huge.

**Comment by zj8487** [comment]
+1 for support grpc

**Comment by asim** [comment]
Related https://github.com/micro/go-micro/issues/89

**Comment by rooty123** [comment]
It would be great to have gRPC support in the core. Any updates?

**Comment by asim** [comment]
Still thinking about it. It won't be part of the core because they're likely to continually make breaking changes. It may start as a transport plugin first and then a separate rpc plugin later.

**Comment by bruth** [comment]
For reference, here is the document describing the [gRPC protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).

**Comment by asim** [comment]
I'll be taking this on in the next few days. My plan is to start with the client as I wrote it once before with a simple use of the existing grpc code to call grpc.Invoke. On the server side it's basically going to be a top level server implementation that reuses some of what's in grpc-go.

This implementation of go-micro/{client, server} will ignore go-micro/transport and potentially also ignore go-micro/codec since grpc-go implements a simple codec version with Marshal/Unmarshal. It's not ideal but it's a good first step to supporting the grpc protocol. The main goal is to be able to communicate with grpc apps written outside of the micro domain. With our implementation, we lose certain pluggable micro functionality but reap the benefits of the overall architecture, tools, service discovery, etc.

**Comment by asim** [comment]
The work starts here https://github.com/micro/go-plugins/pull/46

**Comment by asim** [comment]
Server https://github.com/micro/go-plugins/pull/62

**Comment by asim** [comment]
OMG ITS COMPLETE!!!!

**Comment by pauldub** [comment]
Congrats! :tada:
