### ISSUE TITLE
How can I set address for RabbitMQ broker when it created manually?

### ISSUE THREAD

**Issue by DexterHD** [micro/go-plugins#151]
I'am trying to use RabbitMQ broker, but how can I set address from flags for it, and why exchange replaces by default?

```go
func main(){
    rmq := rabbitmq.NewBroker(rabbitmq.Exchange("test"))
    service := micro.NewService(micro.Broker(rmq))
    service.Init()
    service.Run()
}
```

> ./svc-example --broker=rabbitmq --broker_address=amqp://user:pass@host:5672

This options doesn't work. It just remove my one and create new rabbitmq broker instance and set exchange to default ("micro")

If I remove all options, broker sets to default (http) so I can't use plugins directly with `service`. It works only if I create a plain cmd app without `service` abstraction

**Comment by asim** [comment]
Here's the go-micro code for what the command line does if it finds flags 

```
	// Set the broker
	if name := ctx.String("broker"); len(name) > 0 || len(ctx.String("broker_address")) > 0 {
		if len(name) == 0 {
			name = defaultBroker
		}

		if b, ok := c.opts.Brokers[name]; ok {
			n := b(broker.Addrs(strings.Split(ctx.String("broker_address"), ",")...))
			*c.opts.Broker = n
		} else {
			return fmt.Errorf("Broker %s not found", name)
		}

		serverOpts = append(serverOpts, server.Broker(*c.opts.Broker))
		clientOpts = append(clientOpts, client.Broker(*c.opts.Broker))
	}
```
You can see it's a very simple initialisation for switching out plugins. It's not setup to let you specify a broker in code and then switch address on the command line. It's taking the plugin and create a new broker, then setting the address. If you end up doing custom initialisation then the expectation is that you'll set the address yourself also.

**Comment by DexterHD** [comment]
Ок, so I need to set address myself. But how? When I'm trying something like this, and start service without parameters:

```go
func main() {
	
	rmq := rabbitmq.NewBroker(rabbitmq.Exchange("default"))
	
	service := micro.NewService(
		micro.Name(ServiceName),
		micro.Flags(
			cli.StringFlag{
				Name:   "rabbit-dsn",
				Value:  "amqp://user:password@rabbit-0:5672",
				Usage:  "Rabbit DSN",
				EnvVar: "RABBIT_DSN",
			},
		),
		micro.Broker(rmq),
	)

	service.Init(
		micro.Action(func(c *cli.Context) {

			rmq.Init(broker.Addrs(c.String("rabbit-dsn")))

			if err := service.Run(); err != nil {
				log.Fatalf("couldn't run service %s, reason: %v", ServiceName, err)
			}
		}),
	)
}
```

I have an error:

> 2018/02/17 14:41:35 Listening on [::]:49014
> 2018/02/17 14:41:35 couldn't run service ***, reason: dial tcp 127.0.0.1:5672: getsockopt: connection refused

Micro always use `DefaultRabbitURL` because connection creates inside `NewBroker` constructor:
https://github.com/micro/go-plugins/blob/master/broker/rabbitmq/rabbitmq.go#L168
And when I do `rmq.Init()` it doesn't work because connection already created.

So I can't use service Flags to Init a broker. I can only init it on creation, but in `main` function I can't get `cli.Context`. Maybe connection must be recreated inside `rabbitmq.Init()`? 

Or maybe I'am doing all this stuff wrong way...

**Comment by asim** [comment]
Ideally we should create the connection on Connect as opposed to NewBroker or in Init

**Comment by DexterHD** [comment]
Ok. I made some refactoring. Is it looks good now?

**Comment by asim** [comment]
Right idea but it needs to factor in what the user might do if they don't honour the expected usage.

**Comment by asim** [comment]
Merged PR. Please close issue if resolved.
