### ISSUE TITLE
grpc err?

### ISSUE THREAD

**Issue by artong0416** [micro/go-plugins#158]
I get an error like this:
`../../micro/go-plugins/server/grpc/grpc.go:156:5: cannot use func literal (type func("context".Context, string) "context".Context) as type func("golang.org/x/net/context".Context, string) "golang.org/x/net/context".Context in argument to st.HandleStreams`

**Comment by asim** [comment]
We're now supporting go versions 1.9 and 1.10.x. You need to upgrade the version of Go to fix this error. It depends on go's aliasing of context in 1.9.
