### ISSUE TITLE
There is problem with the grpc server’s memory leak.

### ISSUE THREAD

**Issue by dpominov** [micro/go-plugins#162]
There is problem with the grpc server’s memory leak in case of a response preparation takes more time than the gprc client timeout.

In this case, the server sends a response to the client has been already disconnected by timeout and the server waiting for acknowledgment before the connection timeout, which by default is 2 hours.
Because of this, there are a lot of open connections is created on the server.
Assuming that each grpc request produces a new http2 server as a transport and it has read and write buffers of 32 kbytes each, memory is going to be leaked.

We’ve find out the problem in the case of a long database response, while our microservice began to consume memory more than 2 GB. In common case, microservice consumes 60-80 megabytes.

The problem can be solved by decreasing the timeouts and sizes of the server's http2 buffers. Is it possible to set the parameters for the hhtp2 server?

**Comment by asim** [comment]
We can see an addition to the official grpc framework for this https://github.com/grpc/grpc-go/commit/4318e6475c4b2660f7b8ddb77a4504da77311504#diff-34c6b408d72845d076d47126c29948d1 

So likely we can add a way to support connection timeout. Feel free to PR a fix if you can with the ability to set via options.

**Comment by dpominov** [comment]
I solved the conflicts and refactored my PR. Can you accept it?

**Comment by asim** [comment]
Looking at it, it's not the ideal solution to this. I'll have a further look later. It either requires different naming or we should not actually be exposing access to this transport config.

**Comment by asim** [comment]
PR merged

**Comment by dpominov** [comment]
Thank you very much!
