### ISSUE TITLE
Getting error: NewCallWrapper redeclared in this block

### ISSUE THREAD

**Issue by pjvw1995** [micro/go-plugins#184]
After updating deps, I received the following error: 
```
vendor/github.com/micro/go-plugins/wrapper/trace/opentracing/opentracing.go:84:9: NewCallWrapper.func1 redeclared in this block
	previous declaration at vendor/github.com/micro/go-plugins/wrapper/trace/opentracing/opentracing.go:61:9
```
Same function is declared twice, at line 60 and 83 in https://github.com/micro/go-plugins/blob/master/wrapper/trace/opentracing/opentracing.go.

**Comment by asim** [comment]
That's highly annoying. Someone PRed that change. I've fixed the issue thanks.
