### ISSUE TITLE
Apache Kafka transport support

### ISSUE THREAD

**Issue by Alma-media** [micro/go-plugins#189]
Hi guys!

Thanks a lot for your efforts! Our company is really happy using `go-micro` but we are missing Apache Kafka transport support. So we decided to implement it ourselves. 

We thought that others also might be interested in this and would like to share with the community. 

Please let me know if you guys willing to add this plugin to the repository, and I'll open a PR `go-plugins`.

Regards,
Alex

**Comment by asim** [comment]
Yes the contribution would be appreciated. Please include a dco signoff as `Signed-off-by: John Doe <john.doe@gmail.com>`
