### ISSUE TITLE
Get "invalid character 'U' looking for beginning of value" error when using Kubernetes registry plugin

### ISSUE THREAD

**Issue by foobarsucka** [micro/go-plugins#19]
Deploying the greeter example in Kubernetes using the Kubernetes registry plugin results in the following error when using the API:

```
{"id":"go.micro.client","code":500,"detail":"invalid character 'U' looking for beginning of value","status":"Internal Server Error"}
```

A similar error is presented when using `micro --registry=kubernetes list services` from within the container running the Micro API service in Kubernetes.

**Comment by foobarsucka** [comment]
To clarify, all of the Micro apps are being deployed as pods in my Kubernetes environment, so using `--registry=kubernetes` without using `--registry_address` should work fine, as the default service account is present in the pods. If you think this error has to do with invalid API login credentials, let me know and I'll test to see if passing a registry address helps.

**Comment by nickjackson** [comment]
What version of kubernetes are you using?

**Comment by foobarsucka** [comment]
Kubernetes `v1.2`.
