### ISSUE TITLE
Trace: Add opentracing plugin

### ISSUE THREAD

**Issue by asim** [micro/go-plugins#20]
Add a plugin for opentracing https://github.com/opentracing/opentracing-go

**Comment by Rushit** [comment]
Hi, I am willing to chip-in. Being new on the micro, what will be best starting guide to accomplish this task?

**Comment by asim** [comment]
Hey. This is on hold at the moment. The tracing interface is part of the go-platform which is going to undergo some breaking changes and renaming so probably not the best place to start right now.
