### ISSUE TITLE
re-connect to MQ from broker when session crash

### ISSUE THREAD

**Issue by crazybber** [micro/go-plugins#210]
in case of session broken , do we have the re-connecting mechanisms  for broker ?

**Comment by asim** [comment]
For which broker?

**Comment by CrazyBBer** [comment]
@asim such as : nats  we are using, we don't need Kafka although which has re-connecting mechanisms

**Comment by asim** [comment]
Reconnection logic is quite complex to implement. Doing it on a per broker basis might be inefficient. We need a scalable solution. The broker interface provides a `Connect()` method. If we have a way of tracking connections then we can provide higher level functionality to reconnect, although resubscribe then also poses issues. I'm open to hearing suggestions for solutions.

**Comment by asim** [comment]
No response. Closing.
