### ISSUE TITLE
how to custom rabbitmq's Subscribe with DurableQueue()

### ISSUE THREAD

**Issue by lcySigma** [micro/go-plugins#215]

**Comment by asim** [comment]
```
b := rabbitmq.NewBroker(
  rabbitmq.DurableQueue(),
)

```

**Comment by lcySigma** [comment]
The Code
rmq := rabbitmq.NewBroker(
        rabbitmq.DurableQueue(),
    )

build error:
./main.go:63:30: cannot use rabbitmq.DurableQueue() (type broker.SubscribeOption) as type broker.Option in argument to rabbitmq.NewBroker

**Comment by asim** [comment]
I'm literally reading godoc to give you a response. You can do this yourself. Look at the DurableQueue option. Where is it used? It's a broker subscribe option. So use it when you subscribe.

```
rabbitmq.Subscribe("topic", func(b broker.Publication) error {
  .. do processing
}, rabbitmq.DurableQueue())
```
