### ISSUE TITLE
broker/nats disconnect leaves the object unuseable.

### ISSUE THREAD

**Issue by freman** [micro/go-plugins#218]
When trying to send a quick message via nats in an AfterStop function (making sure the service is deregistered and otherwise unuseable) the nats broker plugin won't reconnect due to Disconnect() not setting n.conn = nil

**Comment by asim** [comment]
It's disconnected. Why would we allow a message to be sent?

**Comment by freman** [comment]
We're trying to reconnect after disconnect but connect exits early if Conn isn't nil.

We're sending out final state information After stopping, it's important that it's done after the service has shut down so there's no further changes to state.

**Comment by asim** [comment]
Would it not make more sense to check if it's connected in Connect? Your change will now cause panics to happen if Disconnect, Publish or Subscribe are called after disconnect. It's likely a better idea to check the connection in Connect and reconnect if not connected.

**Comment by freman** [comment]
Sure, makes sense, I chose the simplest fix I could without considering other calls. I'll submit a different patch when I get home... Assuming I ever get un-lost and traffic doesn't kill me
