### ISSUE TITLE
header and cors plugin can not work

### ISSUE THREAD

**Issue by super-organism** [micro/go-plugins#227]
I want to set a header "Access-Control-Allow-Headers=X-Requested-With" to http.Response ，but that not work when i used them to run the micro api 
this is the picture
![image](https://user-images.githubusercontent.com/29723072/45746024-cee16780-bc34-11e8-8c30-9f3b581e19b2.png)
the run cmd
![image](https://user-images.githubusercontent.com/29723072/45746094-02bc8d00-bc35-11e8-9dcb-ee7f6cd61e51.png)
the response header
![image](https://user-images.githubusercontent.com/29723072/45746151-24b60f80-bc35-11e8-8e44-28cb99505c70.png)

i print the http.ResponseWriter
![image](https://user-images.githubusercontent.com/29723072/45747368-3b119a80-bc38-11e8-9346-6d6f438a0c23.png)

i think the code in header plugin 
![image](https://user-images.githubusercontent.com/29723072/45747409-5da3b380-bc38-11e8-8b63-dd97a4c1b417.png) is should "w.Header().Set(k, v)"

and  the "plugin.Init()" should run after of the api.ServeHTTP() (micro/api/api.go)  because api.ServeHTTP() will reset the http.ResponseWriter

**Comment by asim** [comment]
It looks like you're trying to set CORS headers. Use the cors plugin rather than the header plugin.

**Comment by super-organism** [comment]
![image](https://user-images.githubusercontent.com/29723072/45790457-88811c80-bcb7-11e8-931f-5e3df650fb34.png)
![image](https://user-images.githubusercontent.com/29723072/45790493-b4040700-bcb7-11e8-882e-3fcc077c7203.png)
![image](https://user-images.githubusercontent.com/29723072/45790553-e4e43c00-bcb7-11e8-8798-50c793c84370.png)

the cors plugin and header plugin can not work  

i think the header is set in plugin  will be reset in api.go

**Comment by asim** [comment]
I don't have time to look at this right now. Feel free to trace the error and PR a fix

**Comment by xiangZgnaix** [comment]
I wonder whether this issue is solved.
I have tried for a long time, but still can't make it work.
Below is my directory structure
![2019-01-24 11 39 34](https://user-images.githubusercontent.com/19362132/51689333-6ca8d100-2031-11e9-851a-2af799e8e23d.png)
And here is my running command
![2019-01-24 11 43 41 1](https://user-images.githubusercontent.com/19362132/51689566-eb057300-2031-11e9-87b6-ecd3b92cf89e.png)

**Comment by phuonghau98** [comment]
Wonder it was solved or not? I spent hours and it is still not able to work right now.

**Comment by AllenKaplan** [comment]
I believe this and https://github.com/micro/go-micro/issues/894 are duplicates
