### ISSUE TITLE
integrate swagger tool with go-micro

### ISSUE THREAD

**Issue by hhstore** [micro/go-plugins#233]
# feature:

- integrate `swagger tool`
- Is there a plan to support it?

### 1. `GRPC`:

- use `.proto` to gen `swagger.json`
- serve `swagger.json`

#### reference:

- https://github.com/go-swagger/go-swagger
- https://github.com/grpc-ecosystem/grpc-gateway

```
#
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway

#
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

```

#### usage:

- https://github.com/micro/examples/blob/master/greeter/api/rest/rest.go
- https://github.com/emicklei/go-restful-openapi/blob/master/examples/user-resource.go

#### require:

- https://github.com/emicklei/go-restful
- https://github.com/emicklei/go-restful-openapi
- https://github.com/emicklei/go-restful-swagger12

**Comment by asim** [comment]
I think a lot of people would probably like this feature. Unfortunately I don't have the time to do this integration at the moment. I welcome help to do it.

**Comment by asim** [comment]
Closing for now. Please PR a useful example or support if you have time.
