### ISSUE TITLE
Did it support re-connect when the connection was closed using etcdv3 ?

### ISSUE THREAD

**Issue by clearcodecn** [micro/go-plugins#237]
There was two problem I has meet !

* I Want to change my etcd server address when the application was running. 
so I must stop old cli and connect to anther when I found address was changed .

* When the server was gone , did it try-to-reconnect to the server ?

**Comment by asim** [comment]
I'm assuming you mean the etcdv3 registry. Reconnect is not supported at this time. The implementation would have to factor this in. Feel free to PR a tested change.
