### ISSUE TITLE
hystrix ConfigureCommand doesn't works

### ISSUE THREAD

**Issue by wotmshuaisi** [micro/go-plugins#240]
what ever timeout value i set, the response time keep on `5000ms` and return below
 `{"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}`,

Server:
![](https://i.imgur.com/3LhYEN8.jpg)

Client:
![image](https://user-images.githubusercontent.com/16408269/48172826-3c0fa000-e33c-11e8-9605-4f43d04b92ab.png)

postman:
![](https://i.imgur.com/LJF3Q0g.jpg)

**Comment by asim** [comment]
The micro client request timeout is 5s. This doesn't change when you configure hystrix. You must also set the micro timeout.

**Comment by wotmshuaisi** [comment]
> The micro client request timeout is 5s. This doesn't change when you configure hystrix. You must also set the micro timeout.

wow , thanks bro!!!

**Comment by wotmshuaisi** [comment]
i'll try it after i off my work
