### ISSUE TITLE
How can I register my go micro service into etcd which has username and password

### ISSUE THREAD

**Issue by YinYongTao** [micro/go-plugins#243]

**Comment by asim** [comment]
This PR adds the ability to set auth credentials https://github.com/micro/go-plugins/commit/a55b559e5857f5b2df82cf3a74ee107fada6634e

```go
r := etcdv3.NewRegistry(
    etcdv3.Auth("user", "pass"),
)
```

**Comment by YinYongTao** [comment]
Thank you very much

**Comment by YinYongTao** [comment]
Thank you very much
In my local project，I do like this：

`type Options struct {
	Addrs     []string
	Timeout   time.Duration
	Secure    bool
	TLSConfig *tls.Config
       // add username
	UserName string
       // add password
	Password string
	Context context.Context
}`

<img width="697" alt="default" src="https://user-images.githubusercontent.com/26930834/48830204-01cbe700-edaf-11e8-832d-67289e87eb27.png">

when new Registry object
`reg := etcdv3.NewRegistry(func(options *registry.Options) {
		options.Addrs = []string{"http://152.61.45.175:2379"}
		options.Username = "user"
		options.Password = "pass"
})`

**Comment by YinYongTao** [comment]
Thank you very much
In my local project，I do like this：
<img width="506" alt="default" src="https://user-images.githubusercontent.com/26930834/48830353-5b341600-edaf-11e8-8b7a-15b1c8d990ed.png">

<img width="571" alt="default" src="https://user-images.githubusercontent.com/26930834/48830411-84ed3d00-edaf-11e8-824e-0ad7e9040d0a.png">

<img width="725" alt="default" src="https://user-images.githubusercontent.com/26930834/48830434-959db300-edaf-11e8-892f-679b9a2dd277.png">
