### ISSUE TITLE
stomp bug

### ISSUE THREAD

**Issue by metooweb** [micro/go-plugins#255]
https://github.com/micro/go-plugins/blob/4fe90d56f259b77fe5d767f8dc06491b5c1f307f/broker/stomp/stomp.go#L207

<pre>
handler(&publication{msg: msg, m: m, topic: topic,broker:r})
</pre>

the publication missed the broker instance ，i waste a lot time for this

**Comment by asim** [comment]
What bug? Why does it matter that it does not have the broker as a field in the publication?
