### ISSUE TITLE
rabbitmq broker option auto reset,  exchange name not working

### ISSUE THREAD

**Issue by laoqiu** [micro/go-plugins#260]
look this:
```
rmq := rabbitmq.NewBroker(rabbitmq.Exchange("exchange.cn.meyoung.srv"))
service := micro.NewService(
...
micro.Broker(rmq),
)


```
and  go run main.go --broker=rabbitmq --broker_address=xxxx

see the broker options logs: (rabbitmq.go 270: fmt.Println(options))

```
{[] false <nil> <nil> context.Background.WithValue(rabbitmq.exchangeKey{}, "exchange.cn.meyoung.srv")}
{[amqp://guest:guest@192.168.0.4:5672] false <nil> <nil> context.Background}
```

exchangeKey -> have -> nil

how can i fix it?

**Comment by asim** [comment]
Have you updated go-micro? If you specify the broker flag its going to replace your broker. In an update we fixed this.

**Comment by laoqiu** [comment]
oh, yes, it fixed.

Would you like to write some examples, how to use nats and rabbitmq ?

because many configuration methods need to look the source code to understand. 

It's easier to use if you have examples.

**Comment by asim** [comment]
If you'd like to contribute to the documentation here https://github.com/micro/docs please feel free.  Otherwise there are also examples here https://github.com/micro/examples which you can also contribute to.

**Comment by laoqiu** [comment]
ok, i will be try. thx.

**Comment by laoqiu** [comment]
i have new question:
```

		fmt.Println("body", msg.Body)
		if err := handler(&publication{d: msg, m: m, t: msg.RoutingKey}); err != nil && !opt.AutoAck {
			msg.Nack(false, requeueOnError)
		}
```
main.go
```
micro.RegisterSubscriber("stock.plan.#", service.Server(), subscriber.Handler, server.SubscriberQueue("queue.cn.meyoung.srv.stock.plan"))
```
I can received rabbitmq message, but subscriber.Handler cant't receive any message.

why?  how to write subscriber.Handler allow params?
