### ISSUE TITLE
rabbitmq broker subscriber.Handler can't receive msg

### ISSUE THREAD

**Issue by laoqiu** [micro/go-plugins#261]
i have new question:
```

		fmt.Println("body", msg.Body)
		if err := handler(&publication{d: msg, m: m, t: msg.RoutingKey}); err != nil && !opt.AutoAck {
			msg.Nack(false, requeueOnError)
		}
```
main.go
```
micro.RegisterSubscriber("stock.plan.#", service.Server(), subscriber.Handler, server.SubscriberQueue("queue.cn.meyoung.srv.stock.plan"))
```
I can received rabbitmq message, but subscriber.Handler cant't receive any message.

why?  how to write subscriber.Handler? 
I can't see any error

@asim

_Originally posted by @laoqiu in https://github.com/micro/go-plugins/issues/260#issuecomment-450115584_

**Comment by asim** [comment]
Does your handler actually have the right method signature to be executed?

**Comment by laoqiu** [comment]
```
err != nil && !opt.AutoAck
```
There no err return if err not AutoAck

rabbitmq message must be "application/json" in Content-Type

**Comment by laoqiu** [comment]
why there ignore the error?
