### ISSUE TITLE
server.Option cannot get the initialized value.

### ISSUE THREAD

**Issue by FerminPan** [micro/go-plugins#264]
server.Option can't get the value, I think Init() should be executed before NewServer().

Init()
https://github.com/micro/go-plugins/blob/master/server/grpc/grpc.go#L331
↓↓↓
NewServer()
https://github.com/micro/go-plugins/blob/master/server/grpc/grpc.go#L615

But the current is the opposite process...

**Comment by FerminPan** [comment]
service := micro.NewService(
		micro.Name("greeter"),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*15),
		micro.WrapHandler(wrap),
             
                //The set value will be lost. @asim 
		grpc.WithTLS(tlsConf),
	)

	service.Init()

**Comment by asim** [comment]
Once a server is created we can't add more values. In this case you're best not to use init. The value is not lost when you call init.
