### ISSUE TITLE
createSubHandler - ignoring error when consuming a message

### ISSUE THREAD

**Issue by IceTheLittle** [micro/go-plugins#265]
Hi,
I am using the pub/sub mechanism with GRPC plugin.
When my consumer recieve a message, so the handler func run without taking into account if there was an error as output.
As a result, every message which might be courrpted is autoAcked by default which is a serious problem.

inside /micro/go-plugins/server/grpc/subscriber.go

```
func (g *grpcServer) createSubHandler(sb *subscriber, opts server.Options) broker.Handler {
      ....
      ....
      g.wg.Add(1)
      go func() {
        defer g.wg.Done()
        fn(ctx, &rpcMessage{
          topic:       sb.topic,
          contentType: ct,
          payload:     req.Interface(),
        })
      }()
    }
    return nil
}
```

In addition, fn func is executed without waiting for it to finish with ‘g.wg.wait()’ for example.

Is anybody aware of it?
I have fixed that, so I can commit it and open PR.

Thanks,
Daniel

**Comment by asim** [comment]
Wait is called on the whole server for when it shuts down. Done is called after the execution of any message completes. If you want to provide better auto-ack handling feel free to do so.

**Comment by vtolstov** [comment]
@IceTheLittle can you share code ?

**Comment by IceTheLittle** [comment]
Ended up implementing my own auto-ack handling
