### ISSUE TITLE
Can't use "keep-alive" with go-micro

### ISSUE THREAD

**Issue by AlexaKuzhel** [micro/go-plugins#267]
I can't find where in go-micro I can set the properties "keep-alive".

Could you please help with this?

**Comment by asim** [comment]
Keep-live for what?

**Comment by AlexaKuzhel** [comment]
I want to use keepalive ping between service and active client connection using the grpc protocol.

In grpc we have this options (https://godoc.org/google.golang.org/grpc/keepalive)

but I can't find in go-micro how I can configure this.

**Comment by asim** [comment]
We have no keepalive ping checks and there's no current way to configure this. I'd advise you to use grpc if you're looking for this feature right now. It will likely be some time before we incorporate this in micro.

**Comment by AlexaKuzhel** [comment]
Thanks for your answer.
