### ISSUE TITLE
Can't use cors plugin

### ISSUE THREAD

**Issue by xiangZgnaix** [micro/go-plugins#270]
I wonder whether this issue is solved.
I have tried for a long time, but still can't make it work.
Below is my directory structure
![2019-01-24 11 39 34](https://user-images.githubusercontent.com/19362132/51689333-6ca8d100-2031-11e9-851a-2af799e8e23d.png)
And here is my running command
![2019-01-24 11 43 41 1](https://user-images.githubusercontent.com/19362132/51689566-eb057300-2031-11e9-87b6-ecd3b92cf89e.png)

**Comment by xiangZgnaix** [comment]
@asim Hope you can help me! 
Thanks!

**Comment by ilovelili** [comment]
@xiangZgnaix Hi how about this one? Does the plugin really work?

**Comment by ilovelili** [comment]
this plugin is working as expected
