### ISSUE TITLE
NATS streaming messages not ack'd when AutoAck is true

### ISSUE THREAD

**Issue by jakebailey** [micro/go-plugins#276]
I've been testing the NATS streaming broker that was recently committed, and the ack logic seems to be preventing messages from being automatically acknowledged. Looking at the `stanBroker.Subscribe` function:

```go
opt := broker.SubscribeOptions{
	AutoAck: true,
}

// ... 

var stanOpts []stan.SubscriptionOption
if opt.AutoAck {
	stanOpts = append(stanOpts, stan.SetManualAckMode())
}
```

This seems to be reversed. If `AutoAck` is true, then the subscription is set to manual ack mode. I've tried negating to `if !opt.AutoAck`, and it appears to work for me locally.

**Comment by vtolstov** [comment]
This is ongoing issue, im waiting @asim answer about 3 ask modes, auto,
manual, and autosuccess, when i have proper decision, i can fix that.

пн, 28 янв. 2019 г., 8:06 Jake Bailey notifications@github.com:

**Comment by vtolstov** [comment]
Or you can add SuccessAutoAck option when subscribe

пн, 28 янв. 2019 г., 10:07 Vasiliy Tolstov vase@selfip.ru:

**Comment by jakebailey** [comment]
I could do that, but there's no way to effectively use a `broker.SubscribeOption` when you're using `micro.NewService`/`micro.RegisterSubscriber`. I had to try all of the brokers until I found one which had the behavior I was looking for with default options (`nsq`).

In any case, I'd rather wait for it to be fully supported than work around bugs, so I'll wait and see.

**Comment by asim** [comment]
To answer the original question. Yes that's a bug. The other commenter in the issue has open PRs for some changes but they're not quite inline with my expectations of how autoack work. I will fix this bug and the other issues can be addressed separately.

**Comment by asim** [comment]
I've merged @vtolstov changes as this fixes the issue. Please report if the bug is fixed for you.

**Comment by jakebailey** [comment]
It does, but that PR went one step too far:

```go
		if err == nil && successAutoAck && !opt.AutoAck {
			msg.Ack()
		} else if err != nil && opt.AutoAck {
			msg.Ack()
		}
```

If the stan subscription wasn't in manual mode, [then the client will acknowledge the message after the handler returns](https://github.com/nats-io/go-nats-streaming/blob/master/stan.go#L755). The above code will do an extra acknowledge call that's not needed, which will return `stan.ErrManualAck` (which is ignored as `msg.Ack()`'s return value is not checked).

I'm guessing the same goes for many of the other brokers modified in that PR with their own auto-ack functionality.

**Comment by asim** [comment]
@vtolstov can you address the issue please

**Comment by asim** [comment]
I've simplified the error handling for the stan plugin. You're right that ack does not need to be called when autoack is enabling, even in the error case.

**Comment by vtolstov** [comment]
It auto ack only if auto ack provided or success auto ack option, that automatic ack if handler returns nil err.

**Comment by vtolstov** [comment]
Success auto ack option automatic enables manual ack. So if you want ack by self or always use needed option.
Or i miss something?

**Comment by vtolstov** [comment]
Ah i understand,i can fix that after go to my notebook.

**Comment by asim** [comment]
I think the naming is a bit confusion.

1. AutoAck should automatically acknowledge messages. In the case of stan because it already automatically acknowledges messages we do not need to do anything.
2. SuccessAutoAck should be renamed to AckOnSuccess to clearly identify what it does. In the case of stan, this disables auto acknowledgment to only ack on success and leave the user to acknowledge on error.

**Comment by vtolstov** [comment]
Asim, how can in you changes you ack if handker returns error, for example you want to drain queue with invalud messages?

**Comment by vtolstov** [comment]
Ok im fine with renaming

**Comment by jakebailey** [comment]
Agreed on `AckOnSuccess`, though I'm not sure what value there is in setting `AutoAck` to `false` in _any_ scenario if the the underlying message's `Ack` function isn't given to the handler (for any broker, not just `stan`).

For `stan` there seem to be only three "valid" configurations:
- `AutoAck` is `true`,
- `AutoAck` is `false`, `AckOnSuccess` is `true` (which sets `stan` to manual ack).
- `AutoAck` is `true` `AckOnSuccess` is `true` (which overrides `AutoAck` and sets `stan` to manual ack).

**Comment by jakebailey** [comment]
Sorry, I had forgotten about `broker.Publication`, which does expose `Ack`, so maybe it could be done generically and I just don't know the right way to do it.

(As for setting the subscribe options not being doable, that's another issue.)

**Comment by vtolstov** [comment]
Yes,you can use broker interface,but in this xase you need to encode and decode by youself.

**Comment by asim** [comment]
The broker was only ever designed as a notification system but people have pushed for it to do more, auto ack, queues, durability, etc. This means the API has never been in a place to accept these settings. The client and server were meant to abstract away the broker and actually reduce the number of features leveraged i.e if you want all these features its likely better to use a system directly rather than through micro.

Redesigning means redefining what the broker is actually used for and also means figuring out how to deal with API leakage from broker to client/server. I personally don't believe the client or server should be exposing direct features of the broker. I think abstractions are there for a reason.

**Comment by vtolstov** [comment]
may be propose some stuff for real business cases that guaranties delivery and have some additional options?

**Comment by jakebailey** [comment]
Since the if was swapped, yes.
