### ISSUE TITLE
bug: grpc tls can not work  in the latest version

### ISSUE THREAD

**Issue by FerminPan** [micro/go-plugins#289]
```
service := grpc.NewService(
    ...
    grpc.WithTLS(tlsConf),
)
```
This codes work fine in go-plugins(v0.15.0)

**Comment by asim** [comment]
Can you trace the issue?

**Comment by ExpressionVisitor** [comment]
Thank you very much! 

The problem has been fixed
https://github.com/micro/go-plugins/blob/master/server/grpc/grpc.go#L351

**Comment by asim** [comment]
Closing issue
