### ISSUE TITLE
broker subscribe not effact

### ISSUE THREAD

**Issue by cdongyang** [micro/go-plugins#291]
https://github.com/micro/go-plugins/blob/841c06a57946a2a01d53af22c8bb3faee9f585b5/server/http/http.go#L289
The broker.Connect() should run before server.Register() ,otherwise it would register ip:0 to registry because of not connect,which cause that the broker subscribe take not effact. And the rpc_server in go-micro/server is first run broker.Connect() and then run server.Register().

**Comment by asim** [comment]
PR was merged tof ix it.
