### ISSUE TITLE
grpc client has 3 type errors when timeout

### ISSUE THREAD

**Issue by jimilong** [micro/go-plugins#311]
I got 3 different type error when the request timeout

1. {"id":"go.micro.client","code":408,"detail":"context deadline exceeded","status":"Request Timeout"}
2. {"id":"","code":0,"detail":"context deadline exceeded","status":""}  
3. context deadline exceeded

**Comment by asim** [comment]
I think we're in the process of fixing this with an updated release

**Comment by asim** [comment]
I think this was resolved
