### ISSUE TITLE
Unable to recover if zookeeper connection fails

### ISSUE THREAD

**Issue by mmkamburova** [micro/go-plugins#312]
Hello,

We are using the zookeeper plugin for service registry and we need to be able to recover from errors like this:

Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
zk: could not connect to a server

We saw that during the connection on error it is called log.Fatal which calls os.Exit(1) at the end .. Is it possible to return the error instead and not exiting from the program?

**Comment by asim** [comment]
Please PR a fix for this. In the case of initialisation there's no way to return an error so it would only be logged.

**Comment by mmkamburova** [comment]
PR initiated: https://github.com/micro/go-plugins/pull/452
