### ISSUE TITLE
error loading module requirements

### ISSUE THREAD

**Issue by cbwfree** [micro/go-plugins#313]
`go get github.com/micro/go-plugins@v1.1.0`
```
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding github.com/remyoudompheng/bigfft v0.0.0-20170806203942-52369c62f446
go: finding golang.org/x/exp v0.0.0-20190312203227-4b39c73a6495
go: finding modernc.org/mathutil v1.0.0
go: finding modernc.org/strutil v1.0.0
go: finding modernc.org/xc v1.0.0
go: finding modernc.org/cc v1.0.0
go: finding modernc.org/golex v1.0.0
go: finding gonum.org/v1/gonum v0.0.0-20190331200053-3d26580ed485
go: error loading module requirements
```

**Comment by fitzix** [comment]
The problem is that some package in dependency graph is still referencing github.com/golang/lint, rather than golang.org/x/lint.
see https://github.com/golang/lint/issues/446#issuecomment-483638233

**Comment by asim** [comment]
I believe this is fixed

**Comment by dmitrymomot** [comment]
If someone has the same issue, it should help:
`$ go mod edit -replace github.com/testcontainers/testcontainer-go@v0.0.2=github.com/testcontainers/testcontainers-go@latest`
and 
`$ go mod edit -replace github.com/golang/lint=golang.org/x/lint@latest`
