### ISSUE TITLE
Goroutine leak in grpcClient.Call when the timeout is exceeded

### ISSUE THREAD

**Issue by ginuerzh** [micro/go-plugins#314]
The `callOpts.Retries` is default to 0, then `ch := make(chan error, callOpts.Retries)` is unbuffered. When the call is timeout, the `ch` will be never read, the goroutine `ch <- call(i)` get stuck.

**Comment by lqczzz** [comment]
> The `callOpts.Retries` is default to 0, then `ch := make(chan error, callOpts.Retries)` is unbuffered. When the call is timeout, the `ch` will be never read, the goroutine `ch <- call(i)` get stuck.

it seems that the default value of `callOpts.Retries` is 1 , defined in :
https://github.com/micro/go-micro/blob/master/client/client.go#L106

**Comment by asim** [comment]
This issue has recently been fixed so we should be able to close this
