### ISSUE TITLE
err:{"id":"","code":0,"detail":"grpc: received message larger than max (2974679040 vs. 4194304)","status":""}

### ISSUE THREAD

**Issue by PengjuDuan** [micro/go-plugins#315]
`
grpc.MaxRecvMsgSize(math.MaxInt32)
grpc3MaxSendMsgSize(math.MaxInt32)
`

does't work

**Comment by asim** [comment]
Do you have more info on this? That's not a very useful line of code.

**Comment by vtolstov** [comment]
use micro grpc client and server options to set this params
