### ISSUE TITLE
go-micro with grpc doesnot work, and I find something confused

### ISSUE THREAD

**Issue by xiaoDC** [micro/go-plugins#321]
`go-micro` use grpcBroker with Context has registryKey to record the registry, but the `registryKey` is `contextKeyT("github.com/micro/go-micro/registry")`. The code is 
https://github.com/micro/go-micro/blob/master/broker/options.go#L50
https://github.com/micro/go-micro/blob/master/broker/options.go#L97

But `go-plugins` the `registryKey` is 
https://github.com/micro/go-plugins/blob/master/broker/grpc/grpc.go#L64

these are different.

so when get the registry, thr registry is nil
https://github.com/micro/go-plugins/blob/master/broker/grpc/grpc.go#L374

can it work?

**Comment by asim** [comment]
Did you try it? The key is a string meaning it will be the same.

**Comment by xiaoDC** [comment]
yes, i did try it. 

![https://raw.githubusercontent.com/xiaoDC/static/master/WechatIMG52.png]()

**Comment by asim** [comment]
I've changed go-micro/broker registry key to be a string so this should now be fixed.
