### ISSUE TITLE
Wrapper does not work well with gRCP

### ISSUE THREAD

**Issue by tegk** [micro/go-plugins#333]
When I am using the Wrapper by go-micro instead of  an gRCP stream interceptor for token authentication the connection does not terminate fast enough and the client is able to send message to the server. This behaviour does not happen every time and thus seems to be a bug. 
Client log:
```
2019/05/22 11:41:56 Message send to Server:bjiiet7e32ib6pfd00a0

2019/05/22 11:41:56 rpc error: code = Unauthenticated desc = {"id":"bad auth","code":401,"detail":"request could be not authenticated","status":"Unauthorized"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7e7e7a]

```
The wrapper on the serve side looks like this:
```
// New Service
	service := grpc.NewService(
		micro.Name("go.micro.srv.test"),
		micro.WrapHandler(auth.WrapperAuth),
	)


func WrapperAuth(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, resp interface{}) error {
		meta, ok := metadata.FromContext(ctx)
		if !ok {
			return errors.New("bad auth","request could be not authenticated", 401)
		}

		t := meta["authorization"]

		const prefix = "Bearer "
		if !strings.HasPrefix(t, prefix) {
			return errors.New("bad auth","request could be not authenticated", 401)
		}

		tToken := strings.TrimPrefix(t, prefix)
		if tToken != "token123" {
			return errors.New("bad auth","request could be not authenticated", 401)
		}

		log.Log("Authenticating with token: ", meta["authorization"])

		err := fn(ctx, req, resp)
		return err
	}
}
```

**Comment by k1ng440** [comment]
copy the metadata

see: 
https://github.com/micro/go-plugins/blob/master/wrapper/trace/datadog/helper.go#L21

**Comment by k1ng440** [comment]
i cant tell where the `nil pointer` is coming from but seems this causing the problem

```
t, ok  := meta["authorization"]
if ok {
 // do your stuff here.
}

```

**Comment by tegk** [comment]
> i cant tell where the `nil pointer` is coming from but seems this causing the problem
> 
> ```
> t, ok  := meta["authorization"]
> if ok {
>  // do your stuff here.
> }
> ```

Thanks but this does not resolve the fact that the gRPC client send messages on the stream before the connections is authorized.

**Comment by k1ng440** [comment]
maybe try to debug using `req.Endpoint()`

**Comment by asim** [comment]
Has anyone looked at the internal code to see where the wrapper is executed. Is the expectation that this be done before the message is even consumed? I have a feeling there's some sort of expectation of transport level authorisation rather than service level. If you are in the wrapper the message has already been consumed. If you want transport level authorisation this is an entirely different thing and I imagine you'd suffer the same problem with standard grpc. They have transport level credentials which are dealt with before the messages are streamed as a separate usecase.

**Comment by vtolstov** [comment]
please provide full panic log with all traces, or we need to close the issue, as wrapper in grpc works fine for me.
