### ISSUE TITLE
wrong etcd package

### ISSUE THREAD

**Issue by chengjing1181122598** [micro/go-plugins#343]
https://github.com/micro/go-plugins/blob/master/registry/etcdv3/etcdv3.go line 155 uses package "go.etcd.io/etcd/etcdserver/api/v3rpc/rpctypes".But official release version https://github.com/etcd-io/etcd/blob/v3.3.13/clientv3/client.go uses  "github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes".So a error "etcdserver: requested lease not found" occurs.Maybe you use official master branch is the reason.

**Comment by vtolstov** [comment]
i think that this fixed in latest go-plugins, please recheck
