### ISSUE TITLE
Problem building with plugins

### ISSUE THREAD

**Issue by subzerobo** [micro/go-plugins#349]
Hi @asim 

this error shows up when enabling go-plugins in micro projects 
you can see it in this conditions : 

`micro new github.com/myrepo/myservice`
after make proto and replacing these values in go.mod to avoid **go: error loading module requirements** for add go get -u github.com/micro/plugins 

`replace github.com/testcontainers/testcontainer-go => github.com/testcontainers/testcontainers-go v0.0.0-20181115231424-8e868ca12c0f
replace github.com/golang/lint => github.com/golang/lint v0.0.0-20190227174305-8f45f776aaf1
`
eventualy you get go-plugins v1.1.0 as mentioned in [https://github.com/micro/go-plugins/issues/342](#342)  

after enabling any plugin, for example, let's say nats transport 

```
package main

import (
	// nats transport
	_ "github.com/micro/go-plugins/transport/nats"
)
```

and running 

`go run main.go plugin.go` it will result in 👇 

**build command-line-arguments: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
        github.com/hashicorp/consul v1.4.4 (/Users/alikaviani/Projects/go/pkg/mod/github.com/hashicorp/consul@v1.4.4/api)
        github.com/hashicorp/consul/api v1.1.0 (/Users/alikaviani/Projects/go/pkg/mod/github.com/hashicorp/consul/api@v1.1.0)**

**Comment by subzerobo** [comment]
Hi @asim 
it seems that go-plugin project is under development to be compatible with go-micro higher releases
currently you are requiring  github.com/micro/go-micro v1.1.0 in the latest release of [https://github.com/micro/go-plugins/blob/v1.1.0/go.mod](go-plugin 1.1.0) but this version of go-micro (1.1.0) still using consul v1.4.4, not consul/api v1.1.0 which brings above error.

it think in your next release as we can see in your master branch of go-plugins go.mod file you are planing to use `github.com/micro/go-micro v1.3.0` which doesn't use consul 1.4.4 but this is not the only thing needed to be changed as well in `micro/micro v1.2.0` -> brings this error 👇 

```
go: finding github.com/nats-io/go-nats-streaming v0.4.5
go: github.com/nats-io/go-nats-streaming@v0.4.5: unknown revision v0.4.5
go: error loading module requirements
```

**Comment by vtolstov** [comment]
please, check again in latest go-plugins

**Comment by saileifeng** [comment]
u can try it fix.
```
go get -u -v github.com/hashicorp/consul@none
```

**Comment by vtolstov** [comment]
as i see our ci works fine, so this is fixed

**Comment by mytototo** [comment]
Is it possible to release with go mod fixes please ?

**Comment by vtolstov** [comment]
done

**Comment by vtolstov** [comment]
please, try new release v1.1.1
