### ISSUE TITLE
RabbitMQ broker fail-over strategy

### ISSUE THREAD

**Issue by jrsanz1** [micro/go-plugins#35]
Currently rabbitmq plugin only makes use of the first broker address provided during initialization; if unable to connect to the broker instance the application hangs in the broker.Connect function. Would be nice to be able to use the additional broker addresses as back-up during broker.Connect and to execute a fail-over strategy after a unsuccessful publish of a message to achieve HA of pub/sub. This probably also means that the broker would have to subscribe using all the broker addresses to account for this.

**Comment by asim** [comment]
What you're asking for is not a simple change. I can see the potential to add something that cycles through the addresses when there's an issue but probably not advisable to subscribe to all brokers at the same time. RabbitMQ supports clustering and federation which is what should be relied upon for high availability. The cluster can be put behind a haproxy to provide high availability. If a rabbitmq node dies the connection will reinit with the next node, if the entire cluster dies you can have a backup in haproxy config.
