### ISSUE TITLE
marshal error when using google wrappers in proto

### ISSUE THREAD

**Issue by xmlking** [micro/go-plugins#359]
I am using wrapper types from `google/protobuf/wrappers.proto` e.g., `google.protobuf.StringValue`, when calling my handler I am getting following error! 

Repo to reproduce: https://github.com/xmlking/micro-starter-kit
 
Error
```json
{
  "id": "go.micro.rpc",
  "code": 500,
  "detail": "error during request: json: cannot unmarshal string into Go struct field ProfileRequest.avatar of type wrappers.StringValue",
  "status": "Internal Server Error"
}
```

![image](https://user-images.githubusercontent.com/627951/59906728-4445b880-93be-11e9-8e2f-6fa331d66723.png)

**Comment by asim** [comment]
This likely requires the use of jsonpb rather than json to unmarshal the types. We've not cut a release yet which added the change to the json codec.

**Comment by xmlking** [comment]
will v1.7.0 resolve this issue ?

**Comment by asim** [comment]
Try and see?

**Comment by xmlking** [comment]
Awesome Works!!!
