### ISSUE TITLE
registry/kubernetes 20ms increase ping

### ISSUE THREAD

**Issue by clanstyles** [micro/go-plugins#36]
I noticed a 20ms increase using the kubernetes registry. I'm not sure what it is, if you use consul vs kubernetes registry you'll notice the difference as well.

**Comment by asim** [comment]
Do you have any data to support this? Where is the cluster running? What's the configuration? When you say 20ms. An increase where?

**Comment by clanstyles** [comment]
Cluster is at Packet.net
Running Kubernetes

Only change was the registry

Created a demo service called "olddusty" that has an API endpoint "Okay" that responds "Okay" switching from Kubernetes to Consul reduced the load time. 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: olddusty
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: olddusty
    spec:
      containers:
        - name: olddusty
          command: [
            "/old-dusty",
            "--registry=consul",
            "--registry_address=$(REGISTRY_SERVICE_HOST)",
            "--broker=nats",
            "--broker_address=ruser:T0pS3cr3t@nats.default.svc.cluster.local:4222"
          ]
          image: quay.io/xxx/xxx:64053306655e
          imagePullPolicy: Always
      imagePullSecrets:
        - name: xxx
```

**Comment by asim** [comment]
You know its using the kubernetes api to retrieve the registry info right? The client is not doing anything fancy. Just calling ListPods with a filter. The latency is based on however quickly the kubernetes cluster API responds. Have you tried timing a direct request for listing pods against the kubernetes API?

**Comment by clanstyles** [comment]
Given that they have a TTL and a watch, I was under the impression that they would be caching results so it's not looking this up every time.

**Comment by asim** [comment]
The watcher is not used by default in any registry implementation. There no caching by default either. A registry is simply an abstraction over underlying service discovery mechanisms. Watching and caching is left to the user, to further optimised solutions or done so by the caching selector.
