### ISSUE TITLE
Impossibility to use Pod Network Policies with Kubernetes registry plugin

### ISSUE THREAD

**Issue by vesvalo** [micro/go-plugins#361]
Requirement to allow PATCH verb for all pods for the service account, used to run a pod with go-micro app, based on the go-micro's Kubernetes registry plugin, doesn't let to use Pod Network Policies (PNP), because it allows a pod to modify its labels to bypass PNP restrictions.
PNP uses labels to define pods to be isolated, and RBAC implementation allows to grant permissions only for specific names, which is useles for pods.

There should be a way to run go-micro app with kubernetes registry plugin without need to grant PATCH verb to the pod's service account.

**Comment by vtolstov** [comment]
you can use static selector in client and memory registry. If you in clien and server use the same names as you pod all works fine
