### ISSUE TITLE
Make resolve deps hell priority to first

### ISSUE THREAD

**Issue by leaxoy** [micro/go-plugins#363]
I notice some user also fire issue about deps hell, I had create some pr previous, but none of them works well.
In this case, it's so painful to upgrade and maintain this repo, in my project, I had to use `v1.0.0` to avoid deps problem.
In the mean while, I find this repo dep 
```
	github.com/micro/examples v0.1.0
	github.com/micro/go-api v0.7.0 // indirect
	github.com/micro/go-bot v1.1.0 // indirect
	github.com/micro/go-grpc v1.0.1 // indirect
        github.com/micro/go-proxy v0.2.0 // indirect
```

 but I can't find usage in this project, this leads to vary deep deps, like `examples` deps old version `go-micro`, and old `go-micro` would deps `old version micro`, this looks endless😂

I think `example ` should dep `go-plugins`, not the reverse relation, so and `go-grpc`.

**So it's time to solve this?**
Thanks for your work on this great project.

**Comment by leaxoy** [comment]
To archive this, there are some step.
1. run `go mod tidy`, which will make `golang` happy.
2. make ci works well.
3. remove `examples` and `go-grpc`, because `examples` use lots of old deps.
4. alias grpc `client/server/transport` to `go-micro` one.
5. remove duplicated `code/plugin` or alias it.

**Comment by leaxoy** [comment]
@asim

**Comment by vtolstov** [comment]
I do some of the specified stuff today.
Mostly problems with consul and related to it packages.

чт, 27 июн. 2019 г., 12:37 李晓辉 <notifications@github.com>:

**Comment by leaxoy** [comment]
I think not just `consul` problem.

**Comment by leaxoy** [comment]
#342, #347, #349, and many many closed issues

**Comment by vtolstov** [comment]
thanks
