### ISSUE TITLE
cannot find package "github.com/micro/go-plugins/selector/static"

### ISSUE THREAD

**Issue by EnziinSystem** [micro/go-plugins#366]
When I run to get the package:

`go get -u "github.com/micro/kubernetes/go/micro"`

It has an error:
```
package github.com/micro/go-plugins/selector/static: cannot find package "github.com/micro/go-plugins/selector/static" in any of:
	/usr/local/go/src/github.com/micro/go-plugins/selector/static (from $GOROOT)
```

**Comment by asim** [comment]
The kubernetes repo has been deprecated. Please construct this configuration yourself or see the examples repo for the config for this. It may also exist in go-plugins
