### ISSUE TITLE
cannot find module providing package github.com/micro/go-plugins/selector/static

### ISSUE THREAD

**Issue by milanow** [micro/go-plugins#369]
`go get -u github.com/micro/go-plugins` has no issue,
but when I run a .go app it shows error (,
`cannot find module providing package github.com/micro/go-plugins/selector/static` 

in mod file I have,
`require github.com/micro/go-plugins v1.1.1 // indirect`

**Comment by milosgajdos83** [comment]
`selector` package has been moved to `client` so you might want to change your import paths to something like

```
github.com/micro/go-plugins/client/selector/static
```
