### ISSUE TITLE
rename import paths to "go.etcd.io/etcd"

### ISSUE THREAD

**Issue by areThereAnyUserNamesLeft** [micro/go-plugins#372]
When I try to import in the `etcdv3` package I'm seeing this error multiple times when building an existing project with this plugin in a docker (the project builds on my machine but I'm pretty sure I have local versions of the "coreos" package - so it figures that it should build):-

```
../../coreos/etcd/clientv3/auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
```

If you see this issue [https://github.com/etcd-io/etcd/pull/10044](https://github.com/etcd-io/etcd/pull/10044) you can see it explains the issue and the fix. 

I am happy to create a PR but just want a nod to say it is OK just in case I am not aware of something - thanks.

**Comment by vtolstov** [comment]
you can try to create pr and we can check does ci tests passed.

**Comment by vtolstov** [comment]
as etcd is default registry in go-micro now, we try to fix them in go-micro. thanks
