### ISSUE TITLE
Lost config info

### ISSUE THREAD

**Issue by chaffz** [micro/go-plugins#373]
I used a etcd-server as the config center, and I watch it with prefix "/xxx/config".
The problem is:
If I set a key like "/xxx/config/name" => "my-name"
I can't get the value of "name"
```go
                switch action {
		case "delete":
			data = make(map[string]interface{})
		default:
			v, ok := vals.(map[string]interface{}) // Lost info here
			if ok {
				data = v
			}
		}
```
Another case:
If I set a key like "/xxx/config/name" => {"key": "my-name"}
I can't get the value of "name.key" but "key", lost root key "name"

**Comment by vtolstov** [comment]
is this issue is relevant now? if so - please provide minimal example to check
