### ISSUE TITLE
Go mod cannot find revision of nats.io when building

### ISSUE THREAD

**Issue by kjaebker** [micro/go-plugins#374]
I currently have a multi-stage docker build and am getting the following error after running:

```
COPY ./go.mod ./go.sum ./
RUN go mod download
```

```
go: github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d
```

I looked in the nats.go repo and they have no tags for a v1.8.2 or releases that I can see. My go micro services that have already cached this dependency work but any new ones cannot find the revision.

example go.mod for my service:

```
module gitlab.com/****/****-service

go 1.12

require (
	github.com/Masterminds/squirrel v1.1.0
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/golang/protobuf v1.3.1
	github.com/gorilla/mux v1.7.3
	github.com/jmoiron/sqlx v1.2.0 // indirect
	github.com/lib/pq v1.1.1
	github.com/micro/go-micro v1.7.1-0.20190627135301-d8e998ad85fe
	github.com/micro/go-plugins v1.1.1
	gitlab.com/*****/my-private-repo v0.0.0-20190710180804-8226bb7023e8
	golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
)

```

**Comment by vtolstov** [comment]
nats.go have this commit https://github.com/nats-io/nats.go/commit/9f4d16fe7c2d

1.8.2-0.xxxx is pseudo tag that means this is version above 1.8.1 release tag with date af commit and commit rev.

**Comment by kjaebker** [comment]
ok, I see that now... it seems that I can build locally just fine but when I run this in my docker multi-stage build it does not find the commit and then kills the build because it cannot satisfy the build requirements. 

Any help here would be appreciated, but seems this isnt a go-plugins issue so feel free to close as necessary.

Here is the build for reference:

```
# Accept the Go version for the image to be set as a build argument.
# Default to Go 1.12
ARG GO_VERSION=1.12

# First stage: build the executable.
FROM golang:${GO_VERSION}-alpine AS builder

# Create the user and group files that will be used in the running container to
# run the process as an unprivileged user.
RUN mkdir /user && \
    echo 'nobody:x:65534:65534:nobody:/:' > /user/passwd && \
    echo 'nobody:x:65534:' > /user/group

# Install the Certificate-Authority certificates for the app to be able to make
# calls to HTTPS endpoints.
# Git is required for fetching the dependencies.
# openssh-client is needed for fetching private repos
RUN apk add --no-cache ca-certificates git openssh-client

# add auth for getting a private repo
RUN git config --global credential.helper store && echo "https://user:token@gitlab.com" > ~/.git-credentials

# Set the working directory outside $GOPATH to enable the support for modules.
WORKDIR /src

# Fetch dependencies first; they are less susceptible to change on every build
# and will therefore be cached for speeding up the next build
COPY ./go.mod ./go.sum ./
RUN go mod download

# Import the code from the context.
COPY ./ ./

# Build the executable to `/app`. Mark the build as statically linked.
RUN CGO_ENABLED=0 go build \
    -installsuffix 'static' \
    -o /app .

# Final stage: the running container.
FROM scratch AS final

# Import the user and group files from the first stage.
COPY --from=builder /user/group /user/passwd /etc/

# Import the Certificate-Authority certificates for enabling HTTPS.
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Import the compiled executable from the first stage.
COPY --from=builder /app /app

# Declare the port on which the server will be exposed.
# As we're going to run the executable as an unprivileged user, we can't bind
# to ports below 1024.
EXPOSE 8080

# Perform any further action as an unprivileged user.
USER nobody:nobody

# Run the compiled binary.
ENTRYPOINT ["/app"]
```

**Comment by vtolstov** [comment]
if you replace nats with tagged 1.8.1 version does go mod download can run success?

**Comment by kjaebker** [comment]
YES! That fixed my build, I'm not sure why it cant get that commit but appears to have fixed my issues. Thank you very much

**Comment by sudheeshcm** [comment]
@kjaebker @vtolstov  
I still have this issue. Tried removing the packages by deleting the files in the source directory and compiled package folder.
Trying to install **nats** again gave the same error.
```
go: finding github.com/nats-io/nats.go v1.8.2-0.20190607221125-9f4d16fe7c2d
go: github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d
go: error loading module requirements
```

Please help,
Thanks

**Comment by vtolstov** [comment]
@sudheeshcm can you run go get github.com/micro/go-plugins@master ?

**Comment by sudheeshcm** [comment]
@vtolstov 
Didn't help. I just ran that command and this is the output I get.
![image](https://user-images.githubusercontent.com/13598040/61272397-b09cb780-a7c4-11e9-9520-5c0e584da2f2.png)


I also checked the last commit in `~/go/src/github.com/micro/go-plugins` and that's 
```
commit eb737e5f187e7f93493eca0e73561141af69cd09
Author: Aynur Zulkarnaev <50375356+ayzu@users.noreply.github.com>
Date:   Sat Jul 13 14:08:58 2019 +0200
    changed dependency from github.com/nats-io/nats.go v1.8.2-0.20190607221125-9f4d16fe7c2d to github.com/nats-io/nats.go v1.8.1 (#375)
```

**Comment by sudheeshcm** [comment]
Ok, I think I missed the part about adding the replace string in go.mod file. I was assuming that the above commit would take care of it.
Its working fine now.
`replace github.com/nats-io/nats.go v1.8.2-0.20190607221125-9f4d16fe7c2d => github.com/nats-io/nats.go v1.8.1`

Thanks

**Comment by vtolstov** [comment]
i don't think that replace line is needed. may be you have some other that depends on nats with invalid comit
