### ISSUE TITLE
Run with broker plugin nsq will cause flag output and exit

### ISSUE THREAD

**Issue by hellodudu** [micro/go-plugins#376]
There is no problem with broker=http:

        MICRO_BROKER=http MICRO_TRANSPORT=grpc go run main.go

#When changing broker to nsq, it will print flags and exit:

        MICRO_BROKER=nsq MICRO_TRANSPORT=grpc go run main.go

output:

➜  data_mgr MICRO_BROKER=nsq MICRO_TRANSPORT=grpc go run main.go
NAME:
    - a go-micro service

USAGE:
   main [global options] command [command options] [arguments...]

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --client value                  Client for go-micro; rpc [$MICRO_CLIENT]
   --client_request_timeout value  Sets the client request timeout. e.g 500ms, 5s, 1m. Default: 5s [$MICRO_CLIENT_REQUEST_TIMEOUT]
   --client_retries value          Sets the client retries. Default: 1 (default: 1) [$MICRO_CLIENT_RETRIES]
   --client_pool_size value        Sets the client connection pool size. Default: 1 (default: 0) [$MICRO_CLIENT_POOL_SIZE]
   --client_pool_ttl value         Sets the client connection pool ttl. e.g 500ms, 5s, 1m. Default: 1m [$MICRO_CLIENT_POOL_TTL]
   --register_ttl value            Register TTL in seconds (default: 0) [$MICRO_REGISTER_TTL]
   --register_interval value       Register interval in seconds (default: 0) [$MICRO_REGISTER_INTERVAL]
   --server value                  Server for go-micro; rpc [$MICRO_SERVER]
   --server_name value             Name of the server. go.micro.srv.example [$MICRO_SERVER_NAME]
   --server_version value          Version of the server. 1.1.0 [$MICRO_SERVER_VERSION]
   --server_id value               Id of the server. Auto-generated if not specified [$MICRO_SERVER_ID]
   --server_address value          Bind address for the server. 127.0.0.1:8080 [$MICRO_SERVER_ADDRESS]
   --server_advertise value        Used instead of the server_address when registering with discovery. 127.0.0.1:8080 [$MICRO_SERVER_ADVERTISE]
   --server_metadata value         A list of key-value pairs defining metadata. version=1.0.0 [$MICRO_SERVER_METADATA]
   --broker value                  Broker for pub/sub. http, nats, rabbitmq [$MICRO_BROKER]
   --broker_address value          Comma-separated list of broker addresses [$MICRO_BROKER_ADDRESS]
   --registry value                Registry for discovery. consul, mdns [$MICRO_REGISTRY]
   --registry_address value        Comma-separated list of registry addresses [$MICRO_REGISTRY_ADDRESS]
   --selector value                Selector used to pick nodes for querying [$MICRO_SELECTOR]
   --transport value               Transport mechanism used; http [$MICRO_TRANSPORT]
   --transport_address value       Comma-separated list of transport addresses [$MICRO_TRANSPORT_ADDRESS]
   --help, -h                      show help
➜  data_mgr

**Comment by asim** [comment]
Have you included the nsq plugin?

**Comment by hellodudu** [comment]
After adding nsq plugin, It works.
Sorry for bothering.
