### ISSUE TITLE
Cannot configure healthCheckUrl for instance health heartbeat check based on eureka registration

### ISSUE THREAD

**Issue by feixiaobo** [micro/go-plugins#379]
The homePageUrl, statusPageUrl, healthCheckUrl, and secureHealthCheckUrl in the eureka configuration cannot be configured, and the registered instance needs to manually specify the Ip. Why can't you get IP registration automatically?

**Comment by vtolstov** [comment]
we don't use eureka in our apps, if the issue is relevant, please, provide pr
