### ISSUE TITLE
v.1.1.1 go mod error loading module

### ISSUE THREAD

**Issue by lubberland** [micro/go-plugins#381]
go: github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d

**Comment by lubberland** [comment]
there is no 1.8.2 for https://github.com/nats-io/nats.go

**Comment by vtolstov** [comment]
i believe that this is fixed in latest 1.2.0 release of go-plugins.
