### ISSUE TITLE
../../github.com/micro/go-plugins/server/grpc/grpc.go:12:14: undefined: "github.com/micro/go-micro/server/grpc".Debug

### ISSUE THREAD

**Issue by jzhongming** [micro/go-plugins#382]
../../github.com/micro/go-plugins/server/grpc/grpc.go:12:14: undefined: "github.com/micro/go-micro/server/grpc".Debug

**Comment by asim** [comment]
We'll cut a new release to update dependencies soon

**Comment by vtolstov** [comment]
grpc client and server officially supported by go-micro. use it from there.
