### ISSUE TITLE
UDP Plugins for Go-micro

### ISSUE THREAD

**Issue by crazybber** [micro/go-plugins#385]
hi @asim :

recently ,i had an active mind ,i found go-micro have no plugins for UDP modules ,such as, transport、service(client,server)、codec. so ,for now, it's uneasy to listen and request UDP  with codec ,in go-micro framework.

it will take a long time to get  to know of  go-micro fully ,,lots of details need to be explored.

i wanna have a question with u and ur team ,here, if someone wanna make udp with codec work in go-mciro, what special work should we know ,in comparison with tcp/http/grpc.  or did someone had make some work with udp in go-micro ? ,maybe i can make a contribution.

**Comment by asim** [comment]
Is UDP something you need support for? There are two paths. You could use the quic transport or the utp transport in go-plugins https://github.com/micro/go-plugins/tree/master/transport/utp. Both use udp as the underlying transport mechanism.

Alternatively implementing a udp transport should be as simple as implementing the transport interface. Feel free to join the slack to discuss further with the community.

**Comment by crazybber** [comment]
@asim 

according to utp transport ,it looks simple to impl a udp transport ,**but is it enough ?** 
i had some confusion with current concept  design and applyment.
for example ：
1、 the rpc_client code  looks like a stream-oriented design .		

```
                  // send request
		if err := stream.Send(req.Request()); err != nil {
			ch <- err
			return
		}
		// recv request
		if err := stream.Recv(resp); err != nil {
			ch <- err
			return
		}
```
in udp case ,udp_client just need to send it without caring receiving .

2、same time, most of code snips looks like a http-oriented design  ，with HEAD section design, most codes with heads fields options handling ,because, usually, UDP didn't have a head concept .

3、basing on some thought like above ,which make me to thinking “to support UDP in go-micro ,maybe i should  implement udp-client、udp-server、udp-transport、udp-service. etc..  ”

all these which gave  me some confusion ,maybe i made a mistake in considering and understanding go-micro around its layer arch and implement art.

where i am wrong about theses in mind? please correct me to figure it out , thanks a lot.

**Comment by vtolstov** [comment]
Why not fix quic transport?
It have security via tls and udp.

**Comment by vtolstov** [comment]
if you need udp transport, please firstly say for what kind of service do they needed.

**Comment by crazybber** [comment]
> Why not fix quic transport?
> It have security via tls and udp.

looks more reasonable, but lots of work need to be done  .

**Comment by crazybber** [comment]
> if you need udp transport, please firstly say for what kind of service do they needed.

when rising  this topic , i was reflecting  some iot edge scenario , in these scene ,edge services usually need to connect to box/gateway/controller by raw TCP/UPD. which is a shortage for current  go-micro.

**Comment by asim** [comment]
go-micro was never initially intended for such a use case. We started with http/rpc. Now we're defaulting to grpc. Our network has pluggable transports so quic also supported. We could support raw sockets but then you have to know there's some encoding there to be done
