### ISSUE TITLE
Etcd Grpc Registry Service error

### ISSUE THREAD

**Issue by yb19890724** [micro/go-plugins#386]
## Micro Service Etcd NewRegistry

> etcd Version: 3.3.13
>  Go Version: go1.12.4
> protoc 3.6.1
> micro   1.8.0
> go-plugins   1.2.0

### proto
```
syntax = "proto3";

package model;

message Request {
    string name = 1;
}


message Response {
    string msg = 1;
}


// 服务接口
service Say {
    rpc Hello(Request) returns (Response) {}
}
```
### main.go

```
type Say struct{}

func (g *Say) Hello(ctx context.Context, req *hello.Request, rsp *hello.Response) error {
	rsp.Msg = "Hello " + req.Name
	return nil
}

func main() {
	
	reg := etcdv3.NewRegistry(func(op *registry.Options){
		op.Addrs = []string{
			"http://127.0.0.1:2379",
		}
	})
	
	service := micro.NewService(
		micro.Name("hello.client"),
		micro.Registry(reg),
	)
	service.Init() 
	
	client := hello.NewSayService("hello.server", service.Client())
	rsp, err := client.Hello(context.TODO(), &hello.Request{Name: "test"})
	
	if err != nil {
		fmt.Println(err)
	}
	
	fmt.Println(rsp.Msg)
}
```
### run script

- etcd error 

> proto: no coders for int
> proto: no encoder for ValueSize int [GetProperties]

**Comment by milosgajdos83** [comment]
Seems related to https://github.com/etcd-io/etcd/issues/10566

Which might have a fix in this PR: https://github.com/etcd-io/etcd/pull/10598

Does not seem related to `go-micro` though

**Comment by yb19890724** [comment]
@milosgajdos83 

So how can I solve this? Waiting for etcd fix?
Or try another version?

**Comment by milosgajdos83** [comment]
To be honest I dont know what the best way to go forward is. Let's bring @vtolstov here.

My gut feeling is telling me the best thing is to use a version of `etcd` which works and wait for the upstream fix.

**Comment by yb19890724** [comment]
@milosgajdos83 thx

**Comment by vtolstov** [comment]
we can pin version in go-plugins repo, but i'm prefer to wait then etcd 3.4  is released.

**Comment by itcuihao** [comment]
How do I get an etcd from a config file?

**Comment by vtolstov** [comment]
use etcd registry in go-micro, it have pinned version in go.mod that work fine.
