### ISSUE TITLE
rpc client error: "id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"

### ISSUE THREAD

**Issue by ZiyunYang** [micro/go-plugins#387]
Hi, I'm new to go-micro and I met a problem.  The feature I want to implement is that the client implements Call function to get certificates from the server every 5mins. If any certificates changes in server, the server Pub the event to the client and the client Sub the event. I implement the feature by using default rpc client+server and NATs registry, stan broker and NATs transport plugins. 
The problem is when client implements Call function every 30 seconds, it fails on the client side with error: "id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout". This error has nothing to do with the Call interval. And NATs seems to work normal.

My questions are:
1. Do you think the cause of the problem is similar to this issue?
https://github.com/micro/go-plugins/issues/200
Or can you give a hint how to debug….

2. Do you think my design is reasonable? Should I consider using gRPC stream since the client and server communicate in both directions.

Thanks and look forward to your reply.

**Comment by ZiyunYang** [comment]
Here's my code:
https://github.com/ZiyunYang/yzy_gomicro

**Comment by ZiyunYang** [comment]
I figured it out.

**Comment by jiangjinyuan** [comment]
@ZiyunYang Hi, can you tell me how you figure it out?

**Comment by ZiyunYang** [comment]
@jiangjinyuan As for me, it's because two services have the same name... Very embarrassing...
