### ISSUE TITLE
What's the difference between using broker as a plugin(go-plugins/broker) or standalone(go-micro/broker) ?

### ISSUE THREAD

**Issue by ChrysmOre** [micro/go-plugins#389]
What (if any) is the functional difference between the two options?

**Comment by asim** [comment]
Go-plugins is a repo that provides additional plugins for the go-micro/broker interface. The broker along with all other packages in go-micro are interfaces that can be implemented and swapped out. Go-micro provides a few default implementations while go-plugins maintains many additional plugins. Hope that helps.
