### ISSUE TITLE
go get -u github.com/micro/go-plugins/client/selector/static fails

### ISSUE THREAD

**Issue by ss25sand** [micro/go-plugins#390]
When I run the following command:
```
go get -u github.com/micro/go-plugins/client/selector/static
```
I get the following message:
```
...
go: github.com/hashicorp/vault-plugin-auth-pcf@v0.0.0-20190821162840-1c2205826fee: parsing go.mod: unexpected module path "github.com/hashicorp/vault-plugin-auth-cf"
go: finding github.com/google/flatbuffers v1.10.0
go: finding github.com/OneOfOne/xxhash v1.2.5
go: finding github.com/markbates/deplist v1.2.0
go: finding github.com/mattn/go-tty latest
go: finding github.com/influxdata/line-protocol latest
go: finding github.com/ajstarks/deck latest
go get: error loading module requirements
```
I believe the error is caused by the fact that https://github.com/hashicorp/vault-plugin-auth-cf have renamed their repo 6 days ago, which must mean that this project is not pulling in the correct package. I don't think I have a work around since that dependency doesn't have previous release version for me or this project to fall back on.

**Comment by vtolstov** [comment]
i'm prefer complete drop consul stuff. their breaks go-micro and go-plugins too often.
please try to add to you go.mod file
replace github.com/hashicorp/vault-plugin-auth-pcf => github.com/hashicorp/vault-plugin-auth-cf master

**Comment by vtolstov** [comment]
don't use go get -u, only go get xxx@version
