### ISSUE TITLE
The grpc connection is not closed when it completes

### ISSUE THREAD

**Issue by marcosxz** [micro/go-plugins#393]
File : https://github.com/micro/go-plugins/blob/master/broker/grpc/grpc.go
Line: 433
Desc: The grpc connection is not closed when it completes

**Comment by vtolstov** [comment]
yes, this is needs to be fixed, thanks

**Comment by vtolstov** [comment]
please check the latest master of github.com/micro/go-plugins/broker/grpc/v2@master
