### ISSUE TITLE
Rate limiting issues

### ISSUE THREAD

**Issue by ctaccel** [micro/go-plugins#395]
1. how to set rate limiting on API gateway? I see the rate limiting is only set on node, now i need set /abc API with 1 QPS, but if i have N node, now the QPS can be N 

2. how to set rate limiting for user/token?

**Comment by vtolstov** [comment]
you need to write own ratelimiting code. because only you known how set/get info for user and his token

**Comment by ctaccel** [comment]
@vtolstov thanks for your reply, i see what you mean, there will be a same issue as issue 1. 
Each node will have a token set copy, maybe i should write code on api gateway

**Comment by vtolstov** [comment]
for feature control and easy to use - i'm recommend to write dedicated microservice for quota
so you have store (in-memory/persistent) for each user/token pair. in apigw you can call this quota service via wrapper and check does user have enough resources to get his data. if not - return 429 with message.

**Comment by ctaccel** [comment]
yeah, as your mentioned, we should customize the apigw. thanks
