### ISSUE TITLE
mqtt options missing

### ISSUE THREAD

**Issue by icwr** [micro/go-plugins#398]
hi, i am trying to use the mqtt plugin but it looks like some options are missing or not exposed. creating a new broker calls into this newClient function (in broker/mqtt/mqtt.go): 

```
func newClient(addrs []string, opts broker.Options) mqtt.Client {
	// create opts
	cOpts := mqtt.NewClientOptions()
	cOpts.SetClientID(fmt.Sprintf("%d%d", time.Now().UnixNano(), rand.Intn(10)))
	cOpts.SetCleanSession(false)

	// setup tls
	if opts.TLSConfig != nil {
		cOpts.SetTLSConfig(opts.TLSConfig)
	}

	// add brokers
	for _, addr := range addrs {
		cOpts.AddBroker(addr)
	}

	return mqtt.NewClient(cOpts)
}
```

options like username, password, clean session, etc cannot be set by the user. or, perhaps i am missing something?

**Comment by liqiangno1** [comment]
the pub and sub  options（like qos retain etc ）also can not be set by the user，any plan to support it？
