### ISSUE TITLE
Quorum for nats registry

### ISSUE THREAD

**Issue by phifty** [micro/go-plugins#40]
The nats registry is currently working with a broadcast approach. It performs a call for services and waits a configured timeout T for answers. The approach is elegant in the way, that it removes the need of keeping a service-list up-to-date. But a consequence is that each request takes at least T time plus the request itself.

In our setup we run into problems with this. In a few cases the services are really busy and none is responding within the timeout. But if we increase the timeout, latency is added to all requests.

My suggestion is now to add a configurable quorum (how many services should at least answer). The broadcast procedure would abort if the quorum is reached or the timeout is hit. That way we could increase the timeout without slowing down all requests.

Any thoughts on this?

**Comment by asim** [comment]
Yea that sounds like a sane idea. I'll put something together and PR in a bit. Should be fairly simple.

**Comment by phifty** [comment]
Great! Actually, I've started coding it. Will also provide a pull request soon.

**Comment by asim** [comment]
Closing now since it's done.
