### ISSUE TITLE
How to set my exchange broker is the default RabbitMq exchange?

### ISSUE THREAD

**Issue by HuyTikii** [micro/go-plugins#402]
Hi,
In my project, I need to publish message to my queue which isn't bound to the specific exchanges. RabbitMQ doc told that: "The default exchange is a pre-declared direct exchange with no name, usually referred by an empty string". I used go-plugins/broker/rabbitmq to do it, but it isn't work.
I looked at the go-plugin code and I see that if the exchange string is empty, go-plugin will set exchange is "micro". Can you help me please? 
p/s: sorry about my bad english

func (r *rbroker) getExchange() exchange {

	ex := DefaultExchange

	if e, ok := r.opts.Context.Value(exchangeKey{}).(string); ok {
		ex.name = e
	}

	if d, ok := r.opts.Context.Value(durableExchange{}).(bool); ok {
		ex.durable = d
	}

	return ex
}

**Comment by amrnt** [comment]
Do something like this for registering a subscriber

```go
brkr := broker.NewSubscribeOptions(
	broker.Queue("queue.name.default"),
	broker.DisableAutoAck(),
	rabbitmq.RequeueOnError(),
	rabbitmq.DurableQueue(),
	rabbitmq.AckOnSuccess(),
)

// Register a subscriber
micro.RegisterSubscriber(
	"tobic",
	service.Server(),
	new(subscriberPkg.Handler),
	server.DisableAutoAck(),
	server.SubscriberQueue("queue.name.default"),
	server.SubscriberContext(brkr.Context),
)
```

**Comment by HuyTikii** [comment]
I want to use the "default rabbitmq exchange", It is a empty string (exchange_name = ""). It means I will regester the broker like:

```
b := rabbitmq.NewBroker(
	broker.Addrs("URL"),
	rabbitmq.Exchange(""),   <--- ex.name = "" , so: len(ex.name) = 0
	rabbitmq.DurableExchange(),
)
```

But when we run Connect() function, the exchange name will be overwritten by "micro":

```
var (
	DefaultExchange = exchange{
		name: "micro",
	}
        ...
)
...
if len(ex.name) == 0 {
		ex = DefaultExchange
	}
...
```

**Comment by HuyTikii** [comment]
> Do something like this for registering a subscriber
> 
> ```go
> brkr := broker.NewSubscribeOptions(
> 	broker.Queue("queue.name.default"),
> 	broker.DisableAutoAck(),
> 	rabbitmq.RequeueOnError(),
> 	rabbitmq.DurableQueue(),
> 	rabbitmq.AckOnSuccess(),
> )
> 
> // Register a subscriber
> micro.RegisterSubscriber(
> 	"tobic",
> 	service.Server(),
> 	new(subscriberPkg.Handler),
> 	server.DisableAutoAck(),
> 	server.SubscriberQueue("queue.name.default"),
> 	server.SubscriberContext(brkr.Context),
> )
> ```
> 
> and for regestering the broker for the service
> 
> ```go
> b := rabbitmq.NewBroker(
> 	broker.Addrs("URL"),
> 	rabbitmq.Exchange("exchange_name"),
> 	rabbitmq.DurableExchange(),
> )
> 
> if err := b.Init(); err != nil {
> 	log.Fatalf("Broker Init error: %v", err)
> }
> 
> if err := b.Connect(); err != nil {
> 	log.Fatalf("Broker Connect error: %v", err)
> }
> 
> // then you have this option to pass 
> micro.Broker(b)
> ```

I want to use the "default rabbitmq exchange", It is a empty string (exchange_name = ""). It means I will regester the broker like:

```
b := rabbitmq.NewBroker(
	broker.Addrs("URL"),
	rabbitmq.Exchange(""),   <--- ex.name = "" , so: len(ex.name) = 0
	rabbitmq.DurableExchange(),
)
```

But when we run Connect() function, the exchange name will be overwritten by "micro" string:

```
var (
	DefaultExchange = exchange{
		name: "micro",
	}
        ...
)
...
if len(ex.name) == 0 {
		ex = DefaultExchange
	}
...
```

**Comment by amrnt** [comment]
I understand your point now. You just want to use `""` as your exchange and in micro it checks if `len < 1` it will set default name for it. So my comment before doesn't really solve it for you :)

**Comment by vtolstov** [comment]
now it fixed in go-plugins master, please update
