### ISSUE TITLE
how to use micro.RegisterSubscriber to rabbitmq.DurableQueue()

### ISSUE THREAD

**Issue by quexer** [micro/go-plugins#410]
hi, We're looking for the solution for a durable subscriber with rabbitmq plugin.

in `rabbitmq/options.go`, there is a `durableQueue` option

```
// DurableQueue creates a durable queue when subscribing.
func DurableQueue() broker.SubscribeOption {
	return setSubscribeOption(durableQueueKey{}, true)
}
```

how to use it with this method ?

```
micro.RegisterSubscriber("com.xx.event", service.Server(),  handler)
```

thanks!

**Comment by eddiewang** [comment]
@quexer did you ever get this working? i was playing around with this a few weeks back and if I set a durable queue then the topics would not longer work properly.

**Comment by quexer** [comment]
no.

The `broker.SubscribeOption` can apply for `broker.Subscribe` only. So you can't use it with `micro.RegisterSubscriber`.
