### ISSUE TITLE
go get -v github.com/micro/go-plugins 

### ISSUE THREAD

**Issue by android-coco** [micro/go-plugins#412]
```
go get -v github.com/micro/go-plugins
verifying github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9/go.mod: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9/go.mod: malformed record data
```

**Comment by vtolstov** [comment]
you must pin gogo/protobuf to 1.3.0 or 1.3.1 version in you go.mod file

**Comment by android-coco** [comment]
![image](https://user-images.githubusercontent.com/12714486/67479496-cad21580-f690-11e9-905a-60cde1394e7d.png)

**Comment by vtolstov** [comment]
Please provide full go.mod file

**Comment by Seppone** [comment]
It should work by adding a replace statement.

`replace github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.1`

**Comment by android-coco** [comment]
module qp_web_server

go 1.12

require (
	github.com/cihub/seelog v0.0.0-20170130134532-f561c5e57575
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/elazarl/goproxy v0.0.0-20191011121108-aa519ddbe484 // indirect
	github.com/gin-contrib/cors v1.3.0
	github.com/gin-gonic/gin v1.4.0
	github.com/go-redis/redis v6.15.6+incompatible
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/golang/protobuf v1.3.2
	github.com/gorilla/websocket v1.4.1
	github.com/jinzhu/gorm v1.9.11
	github.com/micro/go-micro v1.13.2
	github.com/parnurzeal/gorequest v0.2.16
	gopkg.in/yaml.v2 v2.2.4
	moul.io/http2curl v1.0.0 // indirect
)

**Comment by android-coco** [comment]
> It should work by adding a replace statement.
> 
> `replace github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.1`
