### ISSUE TITLE
import _ "github.com/micro/go-plugins/registry/consul"

### ISSUE THREAD

**Issue by Haleluak** [micro/go-plugins#413]
go version 1.13

use go mod
when import  _ "github.com/micro/go-plugins/registry/consul" file plugin.go

terminal print:

go get github.com/micro/go-plugins/registry/consul: module github.com/micro/go-plugins@upgrade (v1.3.0) found, but does not contain package github.com/micro/go-plugins/registry/consul

**Comment by andrew-jones** [comment]
I've got a similar issue, can we tag a release of go-plugins with the consul plugin if its been removed from go-micro and tagged?

**Comment by asim** [comment]
https://github.com/micro/go-plugins/releases/tag/v1.4.0
