### ISSUE TITLE
can not install go-plugins

### ISSUE THREAD

**Issue by mylonly** [micro/go-plugins#416]
go version: go1.13.3 darwin/amd64

exec `go get github.com/micro/go-plugins `

`        
verifying github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9/go.mod: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9/go.mod: reading https://sum.golang.org/lookup/github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: 410 Gone`

**Comment by yaoliu** [comment]
通过在go.mod里使用replace解决了
replace github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.0
我暂时用这个方法解决了

**Comment by ta2swu** [comment]
> 
> 
> 通过在go.mod里使用replace解决了
> replace github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.0
> 我暂时用这个方法解决了

hi @yaoliu
I Replaced  but it's not working at all

**Comment by AllenKaplan** [comment]
Should be fixed with 1.5.1

**Comment by vtolstov** [comment]
try the latest master of go-plugins please
