### ISSUE TITLE
Error using Micro API with CORS

### ISSUE THREAD

**Issue by AllenKaplan** [micro/go-plugins#419]
Hello, I have been having an issue using the CORS plugin for micro. 

My use case in which I am using CORS is for making requests from my development vue.js front end. Without CORS, I do not get an error in postman, but with the CORS plugin I get the same error as my web browser.

I rebuilt the binary and I am able to run with the correct flags. Without the CORS built micro binary, I am able to successfully make the GET request of http://localhost:8080/rfq/GetRFQbyUser?id="1" but when using a micro binary with the CORS plugin (which I believe is correctly built as the CORS flags show in micro --help) I get the following error returned:

with `--handler=api`

```
{
    "id": "go.micro.client",
    "code": 500,
    "detail": "Bad Request: HTTP status code 400; transport: received the unexpected content-type \"text/plain; charset=utf-8\"",
    "status": "Internal Server Error"
}
```

with `--handler=rpc` (done using post with body of {"id":"1"})
```
{
    "id": "go.micro.client",
    "code": 500,
    "detail": "stream terminated by RST_STREAM with error code: PROTOCOL_ERROR",
    "status": "Internal Server Error"
}
```

I am not getting any CORS headers in the response (might be because of the error or might be a hint to why the error is happening)

From what I guess, there is some text/plain hitting the backend which expects a compatible type for HTTP2. Although, this is just my guess. Any help would be greatly appreciated. Thank you.

**Comment by mikaelmorvan** [comment]
A working example

for main.go file

```
package main

import (
    "github.com/micro/micro/cmd"
)

func main() {
    cmd.Init()
}

```

for plugin.go
```
package main

import (
    // Flags usage of cors plugin micro --cors-allowed-headers=X-Custom-Header --cors-allowed-origins=someotherdomain.com  --cors-allowed-methods=POST
    "github.com/micro/go-plugins/micro/cors"
    "github.com/micro/micro/plugin"
)

func init() {
    // setup cors plugin
    plugin.Register(cors.NewPlugin())
}
```
for env variables
```
export CORS_ALLOWED_METHODS="HEAD,GET,POST,OPTIONS,PUT"
export CORS_ALLOWED_HEADERS="Origin,Content-Type,Accept,Authorization"
export CORS_ALLOWED_ORIGINS="*"
```

To launch the binary you must pass the "api" parameter
