### ISSUE TITLE
go-plugins v1.5.1 Incompatible go-micro v1.17.1

### ISSUE THREAD

**Issue by golyu** [micro/go-plugins#436]
go-plugins@v1.5.1/proxy/http/http.go:254:13:cannot use DefaultRouter (type *Router) as type server.Router in argument to WithRouter:*Router does not implement server.Router (missing ProcessMessage method)
```
// Router handle serving messages
type Router interface {
	// ProcessMessage processes a message
	ProcessMessage(context.Context, Message) error
	// ServeRequest processes a request to completion
	ServeRequest(context.Context, Request, Response) error
}
```
but lack method ProcessMessage in http.go

**Comment by vtolstov** [comment]
try the latest master of go-plugins please
