### ISSUE TITLE
please open stan plugin ConnectionLostCB property

### ISSUE THREAD

**Issue by baotao2006** [micro/go-plugins#439]
if n.connectRetry {
		nopts = append(nopts, stan.SetConnectionLostHandler(n.reconnectCB))
	} else {
		if n.sopts.ConnectionLostCB != nil {
			nopts = append(nopts, stan.SetConnectionLostHandler(n.sopts.ConnectionLostCB))
		}
	}

**Comment by vtolstov** [comment]
You can use full options option.
https://godoc.org/github.com/micro/go-plugins/broker/stan#Options
