### ISSUE TITLE
How to use registry/cache in go-micro

### ISSUE THREAD

**Issue by manjutengale** [micro/go-plugins#441]
can anyone pls share an example of registry cache in go-micro

"github.com/micro/go-micro/registry/cache"
sd := rm.NewRegistry(
		registry.Addrs("http://127.0.0.1:8"),
	)
mycache := cache.New(sd)

and how to pass the mycache variable to service i.e., is it through Init() or in-service definition in micro stub

**Comment by asim** [comment]
```
service := micro.NewService(
    micro.Name("my.service"),
    micro.Registry(mycache),
)
```

**Comment by manjutengale** [comment]
Thank you!!
