### ISSUE TITLE
trace/opencensus plugin not working with gprc

### ISSUE THREAD

**Issue by nFox18** [micro/go-plugins#443]
go-plugins/wrapper/trace/opencensus/opencensus.go  define an custom header which has upper case letters. 
TracePropagationField = "X-Trace-Context"

but gpc chanage all header to lower case.  

grpc-go/metadata/metadata.go

func New(m map[string]string) MD {
	md := MD{}
	for k, val := range m {
		key := strings.ToLower(k)
		md[key] = append(md[key], val)
	}
	return md
}

so opencesus can not find the "X-Trace-Context" header at the server side

**Comment by vtolstov** [comment]
@asim as i remember you fix some issues with uppercase grpc issues in go-micro, does it related to this issue?

**Comment by vtolstov** [comment]
please, try the master   github.com/micro/go-plugins/wrapper/trace/opencensus/v2@master
i'm beleave that isse is fixed via https://github.com/micro/go-plugins/pull/482
