### ISSUE TITLE
[grpc] i want update grpc resp statusCode 

### ISSUE THREAD

**Issue by Gitforxuyang** [micro/go-plugins#446]
How do I customize rpcError

![image](https://user-images.githubusercontent.com/16128584/72235624-2962bc00-360e-11ea-87e5-ad58e97df7ce.png)

**Comment by vtolstov** [comment]
fixed in go-micro repo, now if error is protobuf generated (implements proto.Message) it can be transferred to client and returned to caller with the same type.
