### ISSUE TITLE
unable to add individual plugins  to go.mod

### ISSUE THREAD

**Issue by xmlking** [micro/go-plugins#459]
I added `github.com/go-plugins/config/source/pkger/v2 v2.0.0` to my `go.mod` and when I run `go mod download`  got this error 

```
go: github.com/go-plugins/config/source/pkger/v2@v2.0.0: reading github.com/go-plugins/config/source/pkger/source/pkger/go.mod at revision source/pkger/v2.0.0: unknown revision source/pkger/v2.0.0
```

**Comment by vtolstov** [comment]
fixed in v2.0.1 (github.com/micro/go-plugins/config/source/pkger/v2@v2.0.1)
