### ISSUE TITLE
cannot build service on different transport 

### ISSUE THREAD

**Issue by alienatorZ** [micro/go-plugins#462]
When I follow the instructions on https://micro.mu/docs/plugins-nats.html

I try:
go run main.go --transport=nats --transport_address=127.0.0.1:4222

I get:
build command-line-arguments: cannot load github.com/micro/go-plugins/transport/nats: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/transport/nats

Any idea how to fix this?

Thanks

**Comment by sobiso** [comment]
I have problem w transport nats too

> build command-line-arguments: cannot load github.com/micro/go-plugins/broker/nats: ambiguous import: found github.com/micro/go-plugins/broker/nats in multiple modules:
	github.com/micro/go-plugins v1.5.1 (/Users/kuba/golang/pkg/mod/github.com/micro/go-plugins@v1.5.1/broker/nats)
	github.com/micro/go-plugins/broker/nats v0.0.0-20200119172437-4fe21aa238fd (/Users/kuba/golang/pkg/mod/github.com/micro/go-plugins/broker/nats@v0.0.0-20200119172437-4fe21aa238fd)

**Comment by vtolstov** [comment]
you must use go-micro/v2@master and go-plugins/broker/nats/v2 and go-plugins/transport/nats/v2
