### ISSUE TITLE
when I rebuild micro error happen

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/go-plugins#463]
panic: proto: duplicate enum registered: go.micro.registry.EventType

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
	/home/go/pkg/mod/github.com/golang/protobuf@v1.3.2/proto/properties.go:458
github.com/micro/go-micro/registry/service/proto.init.0()
	/home/go/pkg/mod/github.com/micro/go-micro@v1.18.0/registry/service/proto/registry.pb.go:700 +0x418

**Comment by vtolstov** [comment]
try to pull latest master of go-micro, micro, and micro/cli

**Comment by bluedragonflyliu** [comment]
I have try, no use but have a other error when I go get -u github.com/micro/micro

 upgrading github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e: module github.com/coreos/go-systemd: reading https://goproxy.io/github.com/coreos/go-systemd/@v/list: 404 Not Found

**Comment by vtolstov** [comment]
don't do go get -u , it always update all deps and all things broken

**Comment by bluedragonflyliu** [comment]
where the /registry/consul had moved can't find in github.com/micro/go-plugins

**Comment by vtolstov** [comment]
it still here in registry/consul

**Comment by bluedragonflyliu** [comment]
it seem that depends version conflict, headache i can't solve,if install in a  whole new environment that will happen, and can't rollback an old version eg 1.9.1.

**Comment by vtolstov** [comment]
to install needed version you must use go get with micro/micro/v2@master micro/go-micro/v2@master micro/go-plugins/registry/consul/v2@master and so

**Comment by vtolstov** [comment]
we have v2 of go-micro in not fine state when release (miss that it import older package)

**Comment by bluedragonflyliu** [comment]
now can download well but when go build -o micro main.go plugin.go
build command-line-arguments: cannot load github.com/micro/go-plugins/registry/consul: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/registry/consul

**Comment by vtolstov** [comment]
You need change import paths
From http://github.com/micro/go-plugins/registry/consul to http://github.com/micro/go-plugins/registry/consul/v2

**Comment by bluedragonflyliu** [comment]
does transport/nats could go get use go-plugins/transport/nats/v2 and change paths to  github.com/micro/go-plugins/transport/nats/v2
it have the same trouble with consul

**Comment by bluedragonflyliu** [comment]
after build run 
micro --registry=consul --registry_address=192.168.1.3 api --handle=api 
report
Registry consul not found

**Comment by vtolstov** [comment]
If all imports goes to v2, it must works

**Comment by bluedragonflyliu** [comment]
main.go
package main
  2 
  3 import (
  4     "github.com/micro/go-micro/v2"
  5 )
  6 
  7 func main() {
  8     service := micro.NewService(
  9         // Set service name
 10         micro.Name("micro"),
 11     )
 12 
 13     // Parse CLI flags
 14     service.Init()
 15 }

plugin.go
import (
	_ "github.com/micro/go-plugins/registry/consul/v2"
	_ "github.com/micro/go-plugins/transport/nats/v2"
)

go build -o micro main.go plugin.go

mv micro to $GOPATH/bin
micro --registry=consul --registry_address=192.168.1.3 api --handle=api
Registry consul not found

**Comment by vtolstov** [comment]
consul not is not default registry, so you need to specify it via --plugin to micro command

**Comment by bluedragonflyliu** [comment]
micro --plugin=consul api --address 0.0.0.0:9090 --handler=api
2020-02-07 05:56:45 Error loading plugin consul: Unknown plugin consul

**Comment by hamster1979** [comment]
Its empty!! https://pkg.go.dev/github.com/micro/go-plugins@v2.0.1+incompatible?tab=subdirectories 
Latest version with registry, transport and so on is 1.5.1!!!

**Comment by vtolstov** [comment]
Check v2 version, we switched to go.mod per plugin. May micro have some issues with this

**Comment by hamster1979** [comment]
> Check v2 version,
Empty too. https://pkg.go.dev/github.com/micro/go-plugins/v2@v2.0.0?tab=subdirectories 
require (
	github.com/micro/go-plugins/v2 v2.0.0
)
`user@user-PC:~/golang/projects/data.management/pinger$ go get
build git.watcom.ru/countmax/dmpinger: cannot load github.com/micro/go-plugins/broker/kafka: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/broker/kafka`

**Comment by vtolstov** [comment]
i think that we need to fix micro command...

**Comment by vtolstov** [comment]
try to get micro/micro/v2@master and run 
micro --plugin=registry/consul/v2 api --address 0.0.0.0:9090 --handler=api

**Comment by hamster1979** [comment]
It working only plugin integration through main.go with importing plugin/v2 paths and manually plugin declaration.

Not working plugin integration through plugins.go:
```
build command-line-arguments: cannot load github.com/micro/go-plugins/config/v2: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/config/v2
Makefile:12: recipe for target 'build' failed
make: *** [build] Error 1
```
This command not working too:
```
go get github.com/micro/micro/v2@master
...
...
micro --plugin=registry/consul/v2 api --address 0.0.0.0:9090 --handler=api
# command-line-arguments
/tmp/v2.go:7:2: imported and not used: "github.com/micro/go-plugins/registry/consul/v2" as consul
/tmp/v2.go:14:11: undefined: v2
2020-02-10 12:06:24 Error loading plugin registry/consul/v2: Failed to build plugin v2: exit status 2
```

Your general plugin repo does not contain separate plugin repos.

**Comment by hamster1979** [comment]
Plugins integration working only through main.go with importing plugin/v2 paths and manually plugin declaration (micro.Registry, micro.Broker , etc).

Not working plugins integration through plugins.go - building ok, but execution with flags - "plugin not found"
Micro command not working too:
```
go get github.com/micro/micro/v2@master
...
...
micro --plugin=registry/consul/v2 --plugin=broker/kafka/v2 dmpinger-srv
# command-line-arguments
/tmp/v2.go:7:2: imported and not used: "github.com/micro/go-plugins/registry/consul/v2" as consul
/tmp/v2.go:14:11: undefined: v2
2020-02-10 12:36:58 Error loading plugin registry/consul/v2: Failed to build plugin v2: exit status 2
Failed to build plugin v2: exit status 2
```
Your general plugins repo v2 does not contain separate plugin v2 repos, since this was in version 1.5.1

**Comment by bluedragonflyliu** [comment]
I have the same problem with upstairs

**Comment by vtolstov** [comment]
i'm try to fix this

**Comment by vtolstov** [comment]
can't reproduce
mkdir test
cd test
go mod init test
go: creating new go.mod: module test
go get github.com/micro/micro/v2@master
go: finding github.com master
go: finding github.com/micro master
go: finding github.com/micro/micro master
go: finding github.com/micro/micro/v2 master
go: downloading github.com/micro/micro/v2 v2.0.1-0.20200219080141-e0729da9013a
go: extracting github.com/micro/micro/v2 v2.0.1-0.20200219080141-e0729da9013a
ls
go.mod  go.sum
micro --plugin=registry/consul/v2 --plugin=broker/kafka/v2 dmpinger-srv
2020-02-22 03:08:21 Loaded plugin registry/consul/v2   
2020-02-22 03:08:35 Loaded plugin broker/kafka/v2
```

**Comment by lanrion** [comment]
```
	_ "github.com/micro/go-plugins/registry/etcdv3/v2"
```
It's fine.
