### ISSUE TITLE
Bug: zerolog.ReportCaller reports wrong line

### ISSUE THREAD

**Issue by egyel** [micro/go-plugins#487]
Using logger/zerolog, when the ReportCaller() is set, the logger reports the line number of the plugin.

Setup:
```
import (
  "github.com/micro/go-micro/v2/logger"
  "github.com/micro/go-plugins/logger/zerolog/v2"
)
```
in func main():
```
logger.DefaultLogger = zerolog.NewLogger(
  logger.WithOutput(os.Stdout),
  logger.WithLevel(log.DebugLevel),
  zerolog.ReportCaller(),
  zerolog.WithDevelopmentMode(),
)
```
Log result:
10:42AM INF media/sd/home/egyel/go/pkg/mod/github.com/micro/go-plugins/logger/zerolog/v2@v2.0.3/zerolog.go:138 > Starting [service] go.micro.srv.logtest
10:42AM INF media/sd/home/egyel/go/pkg/mod/github.com/micro/go-plugins/logger/zerolog/v2@v2.0.3/zerolog.go:138 > Server [grpc] Listening on [::]:38049
10:42AM INF media/sd/home/egyel/go/pkg/mod/github.com/micro/go-plugins/logger/zerolog/v2@v2.0.3/zerolog.go:138 > Broker [eats] Connected to [::]:36267
10:42AM INF media/sd/home/egyel/go/pkg/mod/github.com/micro/go-plugins/logger/zerolog/v2@v2.0.3/zerolog.go:138 > Registry [mdns] Registering node: go.micro.srv.logtest-52d19bdf-7cd9-4623-9d86-f565ad1803bc
10:42AM INF media/sd/home/egyel/go/pkg/mod/github.com/micro/go-plugins/logger/zerolog/v2@v2.0.3/zerolog.go:138 > Subscribing to topic: go.micro.srv.logtest
10:42AM DBG media/sd/home/egyel/go/pkg/mod/github.com/micro/go-plugins/logger/zerolog/v2@v2.0.3/**zerolog.go:130** > Received Logtest.Call request

**Comment by vtolstov** [comment]
Yeah, zap have the same issue

**Comment by asim** [comment]
close as wont fix
