### ISSUE TITLE
Close semantic for connectionless transports

### ISSUE THREAD

**Issue by phifty** [micro/go-plugins#49]
On connectionless transport implementations, a `Close` by the client it not recognised by the server. The result is that the `transport.Recv` function blocks forever and that issues a leak of goroutines and memory.

Any suggestions how to fix this?

**Comment by asim** [comment]
There's a few ways to solve this. 

1. Looking at net.Conn there could be the potential to add a Deadline option which allows the Send/Recv actions to timeout after a given period. This would cause Recv to basically unblock and return. 

2. A signalling message can be used within the transport to indicate the client side has closed. I question whether this should be in the transport or at the RPC level.

3. Close the idle socket after a given period. Might have some bad side effect behaviour where people assume a socket lives forever.

**Comment by phifty** [comment]
1) seems like to best solution to me. It doen't require any client activity and can handle cases, where client just "disappear".

3) the described problem would be hard to find.

**Comment by asim** [comment]
Having thought about this for the past day, I think you're right. 1 is the best solution. I'm going to add Deadline as a field in the transport.Options, then implement across the existing transports. Will get this done tomorrow.

**Comment by asim** [comment]
First part here https://github.com/micro/go-micro/pull/112

**Comment by asim** [comment]
PR merged

**Comment by asim** [comment]
https://github.com/micro/go-plugins/pull/51
