### ISSUE TITLE
go-micro auto generate topic in broker(kafka) when run a service.

### ISSUE THREAD

**Issue by Haleluak** [micro/go-plugins#494]
When I was create a service (srv) I see in kafka auto generate topic but didn't data.
![kafka](https://user-images.githubusercontent.com/22067334/75844038-75a8cc00-5e07-11ea-94ce-f1417be7abf2.png)

Can you tell me has option to turn off generate topic when created new services .

**Comment by vtolstov** [comment]
we fixed this is latest go-micro (check muster please)
