### ISSUE TITLE
Ability to publish a message with a given priority

### ISSUE THREAD

**Issue by vonhraban** [micro/go-plugins#503]
Since RabbitMQ version 3.5.0 priority queues are supported - https://www.rabbitmq.com/priority.html

The queue can be declared if `x-max-priority` argument is passed during the queue creation.

I can sucessfully declare a queue with priority support

```	
brkrSub := broker.NewSubscribeOptions(
		broker.DisableAutoAck(),
		rabbitmq.QueueArguments(map[string]interface{}{"x-max-priority": 10}),
	)

	service.Server().Subscribe(
		service.Server().NewSubscriber(
			"mytopic",
			h.Handle,
			server.SubscriberQueue("mytopic.hello"),
			server.SubscriberContext(brkrSub.Context),
		),
	)
```

But how do I publish a message specifying a priority?

I could not find a direct way of passing Priority as either MessageOption or PublishOption, however, it seems there is a way to specify additional options in `client.Publish` context. Am I looking into the correct direction, and if so can you help me a little here?

**Comment by vonhraban** [comment]
Ignore me, answering my own question

```
	brkrSub := broker.NewSubscribeOptions(
		broker.DisableAutoAck(),
		rabbitmq.QueueArguments(map[string]interface{}{"x-max-priority": 10}),
	)

	service.Server().Subscribe(
		service.Server().NewSubscriber(
			"mytopic",
			h.Handle,
			server.SubscriberQueue("mytopic.hello"),
			server.SubscriberContext(brkrSub.Context),
		),
	)
```

**Comment by vtolstov** [comment]
if you have broker, that supports this - you can reuse it. Mostly broker have fifo queue.

**Comment by vonhraban** [comment]
I have rabbitmq as a broker

```
	amqpBroker := rabbitmq.NewBroker()

	serviceName := "rabbit-mq-priority-test"

	service := micro.NewService(
		micro.Name(serviceName),
		micro.RegisterTTL(15*time.Second),
		micro.RegisterInterval(5*time.Second),
		micro.Broker(amqpBroker),
		micro.WrapHandler(opencensus.NewHandlerWrapper()),
		micro.WrapClient(opencensus.NewClientWrapper()),
	)
```

I am confused those where can I specify the priority for the published message?
In pure Go and RabbitMQ library it can be achieved via

```
body := fmt.Sprintf("Message number %d", id)
	err := channel.Publish(
		"",         // exchange
		queue.Name, // routing key
		false,      // mandatory
		false,      // immediate
		amqp.Publishing{
			ContentType: "text/plain",
			Body:        []byte(body),
			Priority:    uint8(priority),
		})
```

**Comment by vonhraban** [comment]
Is it possible to specify priority per message, not globally thorough the service? If you can not specify it individually it kind of defeats the purpose. Unless you have >1 brokers which, if even possible, is pretty cumbersome

**Comment by vonhraban** [comment]
I managed to get this far but to no avail yet

```

func setPriority(ctx context.Context, priority int) client.PublishOption {
	return func(o *client.PublishOptions) {
		o.Context = context.WithValue(ctx, "priority", priority)
	}
}

func publish(ctx context.Context, priority int, counter int) {
	//body := fmt.Sprintf("hello, I am a message %d", counter)
	body := &message.MyTestMessage{
		Message: fmt.Sprintf("Message number %d", counter),
	}

	msg := client.NewMessage(
		topic,
		body,
	)
	if err := client.Publish(ctx, msg, setPriority(ctx, priority)); err != nil {
		fmt.Printf("Cannot publish message: ", err.Error())
		return
	}

	fmt.Printf("Published message %d to %s \n", counter, topic)
}
```

**Comment by vtolstov** [comment]
If we have support for this option in publish inside go-plugins/broker/rabbitmq it must works

**Comment by vonhraban** [comment]
Closing the issue since I am opening another one that is more detailed and has concrete list of issues
