### ISSUE TITLE
dial tcp: address 192.168.100.18:5495:5495: too many colons in address

### ISSUE THREAD

**Issue by sduqlsc** [micro/go-plugins#520]
I have `eureka v2` configured as my micro service, when i tried to invoke my service, it reported the error as below:
```json
{
    "success": false,
    "message": "{\"id\":\"go.micro.client\",\"code\":500,\"detail\":\"connection error: desc = \\\"transport: Error while dialing dial tcp: address 192.168.100.18:5495:5495: too many colons in address\\\"\",\"status\":\"Internal Server Error\"}",
}
```

btw, service seems to register successfully:

```
2020-04-08 17:46:44  level=info Starting [service] xx.micro.xxx
2020-04-08 17:46:44  level=info Server [grpc] Listening on [::]:5495
2020-04-08 17:46:44  level=info Registry [eureka] Registering node: xx.micro.xxx-62d95b50-39c5-4617-8050-6cfb317366d0
```

plus, i noticed that if there was a vpn network card, its address is bound to that, any other way to avoid  it or config in code?

why there was same port append to ip again?

**Comment by vtolstov** [comment]
strange, may be eureka have some issues

**Comment by sduqlsc** [comment]
> strange, may be eureka have some issues

hmm... it's strange, before that, `consul` was good.

**Comment by vtolstov** [comment]
all of them in community maintained repo, we not always can test all of stuff. need to check eureka registry

**Comment by sduqlsc** [comment]
> all of them in community maintained repo, we not always can test all of stuff. need to check eureka registry

I understand, any solution/clue to locate the problem

**Comment by sduqlsc** [comment]
@vtolstov I found the `IPAddr` in the `/micro/go-plugins/registry/eureka/v2/marshalling.go` become as  ip + port:

![image](https://user-images.githubusercontent.com/8055140/78848945-c1bde080-7a45-11ea-9288-46f761a5226d.png)

**Comment by sduqlsc** [comment]
@vtolstov I debuged the code, in my situation, spring cloud was the center, and go-micro-eureka was the client, so after reviewing the code in `micro/go-plugins/registry/eureka/v2/marshalling.go`, i found that `IPAddr` was assinged by `node.Addresss` directly,
![image](https://user-images.githubusercontent.com/8055140/78850096-e36c9700-7a48-11ea-9627-81604db43df6.png)

so back to the `appToService` method, it combined with port directly, that made the ip address append port again:
![image](https://user-images.githubusercontent.com/8055140/78850257-52e28680-7a49-11ea-8130-313b5f95dbe9.png)

**Comment by vtolstov** [comment]
do you want to provide pr?

**Comment by sduqlsc** [comment]
> do you want to provide pr?

Have pushed a commit in the pull request.  I think it was ok in my side, so someone would review it and decide to merge or not?

**Comment by vtolstov** [comment]
yeah, thanks. it merged
