### ISSUE TITLE
etcd3 package update error

### ISSUE THREAD

**Issue by excxapp** [micro/go-plugins#524]
../../../../../go_path/pkg/mod/github.com/coreos/etcd@v3.3.20+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption

github.com/coreos/etcd 
DEPRECATED - please use the official client at https://github.com/coreos/etcd/tree/master/client

but registry is dont upgrade

**Comment by sduqlsc** [comment]
@excxapp hv u used grpc? then i think you should downgrade to 1.26

**Comment by excxapp** [comment]
@sduqlsc yep, i manual replace all etcdv3 from github.com/coreos/etcd to new package.

**Comment by excxapp** [comment]
@sduqlsc yep, i manual replace all etcdv3 from github.com/coreos/etcd to new package.
