### ISSUE TITLE
Compared to go-redis/redis and garyburd/redigo, I chose go-redis/redis

### ISSUE THREAD

**Issue by huangqingcheng** [micro/go-plugins#53]
1. All of them has 1000+ stars;  
2. Former api is more FRIENDLY and less error-prone;  
3. Former look like more effcient and stable;  

If you need, I can help for change all to go-redis/redis.

**Comment by asim** [comment]
I'm not sure there's any reason to change, garyburd/redigo is an adequately maintained project.
