### ISSUE TITLE
p.m header and body is nil in the meanwhile p.km has value

### ISSUE THREAD

**Issue by PhantomMatthew** [micro/go-plugins#538]
My use scenario is as below: 
(1) I use Debezium and kafka/kafka connect to get database changes from Postgres
(2) Kafka has already received the message

I use below code to get subscribe to kafka messages.	`b.Subscribe("dbserver1.public.info",subscriber.NewReceiveMsgHandler().ReceiveMsgHandler)` 
When I tried to get message body in ReceiveMsgHandler function, I used as below 
` m := p.Message()`

Then I found that m.header and m.Body are all nil, in the mean while the km has value from kafka.

Can you help me on this?

**Comment by vtolstov** [comment]
This may means that you message have invalid json.
Ennnable debug log level and specify error handler for broker

вс, 19 апр. 2020 г., 11:03 Jiabei Yuan <notifications@github.com>:
