### ISSUE TITLE
[stan broker] Durable queue group receive out-of-order data when it restarts.

### ISSUE THREAD

**Issue by ZiyunYang** [micro/go-plugins#541]
Hi, I try to implement a pub-sub messaging system by using stan broker. A producer pub messages and several consumers form a durable queue group to sub messages. When producer and consumers are both online, the messages are in-order. Then the producer continue to work while all consumers are shut down. When the consumer restart, messages it receives will be out-of-order.

It this a bug? Or go-micro can not guarantee the order of messages the queue will receive because the pub-sub is asynchronous. If I use stan directly without go-micro, I think the queue group will receive messages in order.

Here are my demos and results.
go-micro+stan demo(out-of-order when consumers restart): https://github.com/ZiyunYang/gomicro_demo/tree/master/gomicro_durablequeue
![image](https://user-images.githubusercontent.com/47910618/79851253-a1076a80-83f7-11ea-8c4a-b8eeca61bd19.png)

stan demo(in-order when consumers restart):
https://github.com/ZiyunYang/gomicro_demo/tree/master/stan_durablequeue
![image](https://user-images.githubusercontent.com/47910618/79851639-2ee35580-83f8-11ea-90cf-140d543be905.png)

**Comment by vtolstov** [comment]
as i know stan not guarantee in order of messages in restart subscriber, check they issues

**Comment by ZiyunYang** [comment]
Relative to this stan issue https://github.com/nats-io/stan.go/issues/308
