### ISSUE TITLE
Make Logger Pluggable

### ISSUE THREAD

**Issue by Allar** [micro/go-plugins#546]
It appears that there is already some work being done to make logging pluggable and I've managed to get the zap logger working in my own microservice, but I'd love to be able to set all services (i.e. what you get when you run `micro server`) to also use zap logging.

It appears though that something like a MICRO_LOGGING env var doesn't exist.

I brought this up in Slack and @asim suggested I make an issue for it so here it is.

**Comment by asim** [comment]
Gonna give this to Vasiliy. I think we can probably add a MICRO_LOGGER env var/switch to set this up like everything else. We'd have to include the zap logger as one of the defaults.

**Comment by vtolstov** [comment]
growing defaults is bad, also not all people love zap, some other prefers zerolog
if this is only micro/micro issue, i think it must created in corresponding repo and in this case this is only micro binary case.

**Comment by itzmanish** [comment]
Wondering if I can set logger.DefaultLogger to zap logger by setting some variable in micro service so that anytime I do logger.Log() It uses zap logger

**Comment by vtolstov** [comment]
@itzmanish you can do that already. Change logger.DefaultLogger to you logger and reuse it in your code
