### ISSUE TITLE
Trace: Add opentelemetry plugin

### ISSUE THREAD

**Issue by Jahangir-Sh** [micro/go-plugins#559]
[OpenTelemetry](https://opentelemetry.io/) provides a single set of APIs, etc., to capture distributed traces and metrics from the instrumented application. Currently, OTel is in beta which [means](https://medium.com/opentelemetry/opentelemetry-is-officially-in-beta-352fa859db10)

> that you can begin integrating OpenTelemetry into your applications and client libraries to capture app-level metrics and distributed traces.

> This beta milestone is a huge accomplishment for the OpenTelemetry community, and every contributor should be proud of the fact that OpenTelemetry is now working and ready to integrate with. This is a great opportunity for the maintainers of client libraries to begin integrating with the OpenTelemetry APIs

Taking into accounting that OpenTracing and OpenCensus [merged](https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0) their efforts and I would suggest creating wrappers as an auto-instrumentation of a `micro` application. 

I am developing wrappers for internal usage and willing to open source it.

**Comment by vtolstov** [comment]
If you provide pr we are happy to review it
