### ISSUE TITLE
com.netflix.client.ClientException: Load balancer does not have available server for client: godemo

### ISSUE THREAD

**Issue by puzhengwu** [micro/go-plugins#562]
package main

import (
	"github.com/micro/go-micro/v2/registry"
	"github.com/micro/go-micro/v2/web"
	"github.com/micro/go-plugins/registry/eureka/v2"

	"gitee.com/larrypu/microdemo/gin-router"
)

func main()  {
	//--registry_address http://192.168.10.79:30418/eureka --registry_address http://192.168.10.79:30463/eureka
	registry := eureka.NewRegistry(func(options *registry.Options) {
		options.Addrs = []string{"http://127.0.0.1:8761/eureka"}
	})
	
	router := gin_router.InitRouter()

	service := web.NewService(
		web.Name("godemo"),
		web.Handler(router),
		web.Registry(registry),
	)

	service.Init()
	service.Run()
}

**Comment by puzhengwu** [comment]
`package main

import (
	"fmt"
	eureka "github.com/xuanbo/eureka-client"
	"net/http"
)

func main() {
	// create eureka client
	client := eureka.NewClient(&eureka.Config{
		DefaultZone:           "http://127.0.0.1:8761/eureka/",
		App:                   "gomoudle",
		Port:                  8506,
		RenewalIntervalInSecs: 10,
		DurationInSecs:        30,
		Metadata: map[string]interface{}{
			"VERSION":              "0.1.0",
			"NODE_GROUP_ID":        0,
			"PRODUCT_CODE":         "DEFAULT",
			"PRODUCT_VERSION_CODE": "DEFAULT",
			"PRODUCT_ENV_CODE":     "DEFAULT",
			"SERVICE_VERSION_CODE": "DEFAULT",
		},
	})
	// start client, register、heartbeat、refresh
	client.Start()

	http.HandleFunc("/", func(writer http.ResponseWriter, request *http.Request) {
		// full applications from eureka server
		//apps := client.Applications
		//b, _ := json.Marshal(apps)
		name := "hello welcome go moudle"

		_, _ = writer.Write([]byte(name))
	})

	http.HandleFunc("/api", func(writer http.ResponseWriter, request *http.Request) {
		// full applications from eureka server
		//apps := client.Applications
		//b, _ := json.Marshal(apps)
		writer.Header().Add("Content-Type", "application/json")
		name := "{\"result\": \"ok\"}"
		_, _ = writer.Write([]byte(name))
	})

	// start http server
	if err := http.ListenAndServe(":8506", nil); err != nil {
		fmt.Println(err)
	}
}`

**Comment by puzhengwu** [comment]
![image](https://user-images.githubusercontent.com/4401394/83959879-b3a90680-a8b4-11ea-8461-e86996c4bfed.png)

**Comment by puzhengwu** [comment]
The status of the godemo project does not show the link. Use the feign of the spring cloud project to link and report an error. The gomodle project is OK. What settings do I lack

**Comment by asim** [comment]
Eureka is mostly unsupported

**Comment by puzhengwu** [comment]
in https://github.com/micro/go-plugins/blob/master/registry/eureka/marshalling.go
library A github.com/hudl/fargo
library B github.com/xuanbo/eureka-client

Could you change library A into Library B? Library A has not been updated for A long time. We have many services using Spring Cloud, so we need A scheme to support Eureka using Golang services
