### ISSUE TITLE
undefined: resolver.ResolveNowOption

### ISSUE THREAD

**Issue by ouyangzhongmin** [micro/go-plugins#575]
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
..\..\pkg\mod\github.com\coreos\etcd@v3.3.22+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
..\..\pkg\mod\github.com\coreos\etcd@v3.3.22+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
..\..\pkg\mod\github.com\coreos\etcd@v3.3.22+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
..\..\pkg\mod\github.com\coreos\etcd@v3.3.22+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions

**Comment by vtolstov** [comment]
add to replace in you go.mod file
github.com/coreos/etcd => github.com/ozonru/etcd v3.3.20-grpc1.27-origmodule+incompatible
google.golang.org/grpc => google.golang.org/grpc v1.27.0

**Comment by ouyangzhongmin** [comment]
nice ! 3q!

**Comment by FlyingOnion** [comment]
If you have grpc, use v1.26.0, `google.golang.org/grpc v1.26.0`.
If you have protobuf, use v1.23.0 `google.golang.org/protobuf v1.23.0`.
Done.
