### ISSUE TITLE
Middleware for validating incoming request.

### ISSUE THREAD

**Issue by itzmanish** [micro/go-plugins#579]
There is validator plugin available with wrapper but due to lack of documentation I am not able to understand it. @vtolstov please give me some guide on using this plugin.

**Comment by vtolstov** [comment]
all wrappers plugged identically via subscribe or handler wrapper. You can check tests files for some of wrappers to understand how it added.
Validation wrapper automatically run func Validate() error on request struct. So if you struct have such method it called before request passed to handler. Mostly it used to automatic validate incoming request and in case of error return micro BadRequest error
