### ISSUE TITLE
msgpack codec request body type 

### ISSUE THREAD

**Issue by qAison** [micro/go-plugins#58]
I have a section of such code

```
cli := client.NewClient(
    client.ContentType("application/msgpack"),
    client.Codec("application/msgpack", msgpackrpc.NewCodec),     
)

length := 4
req := client.NewRequest("rand", "Rand.Digit", length)
cli.Call(context.TODO(), req, reply)
```

return error in: https://github.com/micro/go-plugins/blob/master/codec/msgpackrpc/rpc.go#L56

Request body(value = 4):How to implement msgp.Encodable

Whether it can support any type

**Comment by asim** [comment]
Looking at the way the codec is written. It expects values that are passed n to by of a format that can be encoded/decoded as https://godoc.org/github.com/tinylib/msgp/msgp#Decodable and https://godoc.org/github.com/tinylib/msgp/msgp#Encodable much like a check for proto.Message. 

The msgp library provides a quickstart guide. Much like protobuf, your types have to be compiled into a msgp format. https://github.com/tinylib/msgp
