### ISSUE TITLE
Datadog plugin DOCS

### ISSUE THREAD

**Issue by itzmanish** [micro/go-plugins#580]
I am unable to use datadog plugin. Need some starter code.

**Comment by itzmanish** [comment]
@vtolstov

**Comment by vtolstov** [comment]
if you means trace wrapper, inside package exists test file, so its good starting point.

**Comment by itzmanish** [comment]
I have seen it. But I am confused for client part. I don't use cli client.

**Comment by vtolstov** [comment]
i'm don't understand you problem, server uses subscriber and handler wrappers, client have call wrappers and client can be wrapped.

**Comment by itzmanish** [comment]
Ok. I think I am understanding but I am not sure about one thing how would I get trace data on datadog dashboard?

**Comment by vtolstov** [comment]
i don't know about dashboard but i think that this is not go-micro problem

**Comment by itzmanish** [comment]
Not talking about datadog. If I use opetrace wrapper then how will I get the data to visualize traces?

**Comment by vtolstov** [comment]
Trace spans goes to tracing server. I'm using jaeger it provides ui to
graph service deps and spans info

пн, 3 авг. 2020 г., 18:04 Manish <notifications@github.com>:

**Comment by itzmanish** [comment]
So I only have to run Jaeger or Zipkin to visualize data and nothing else?

**Comment by itzmanish** [comment]
Do you use zipkin + jaeger?

**Comment by vtolstov** [comment]
i'm using jaeger client with jaeger server. but if you send opentracing compat traces this is not problem

**Comment by itzmanish** [comment]
I am doing the same, running jaeger server but I don't see traces. Using handlerwrapper and subsriberwrapper of opentracing plugin.

**Comment by vtolstov** [comment]
You need to create tracer for jaeger and specify needed address of jaeger
server

вт, 4 авг. 2020 г., 16:13 Manish <notifications@github.com>:
