### ISSUE TITLE
Command line arguments not getting printed on Micro

### ISSUE THREAD

**Issue by dinilv** [micro/go-plugins#61]
**_On micro/micro/main.go_**

func init() {
	plugin.Register(ip.NewIPWhitelist())
}

**On ip_whitelist.go**

func (w *whitelist) Handler() plugin.Handler {
	log.Print("handler")
-----------------------------------------------
func NewIPWhitelist(ips ...string) plugin.Plugin {
	log.Print(ips, "Ips for plugin")

**Go build and run the same** 

./micro --ip_whitelist=10.1.1.10,10.1.1.11,10.1.2.0/24 api

[]Iips for plugin

These command line arguments are going empty when i print on the plugin code.

 Also these plugin Handler is not called on every http request received on default port:8080

**Comment by asim** [comment]
Global plugins are not linked into the underlying components yet. You can use api.Register instead of plugin.Register to do it specifically for the api. Usage then becomes `micro api --ip_whitelist=10.1.1.10,10.1.1.11,10.1.2.0/24`

**Comment by asim** [comment]
Issue resolved. https://github.com/micro/micro/commit/fc803a60ca5d5112b0c1a7c06d269c4ab905e724

**Comment by dinilv** [comment]
Plugin is loaded, and everytime its loaded and validated on every api request but command line arguments are still not printed on load ..am i doing something wrong here ?

On micro/micro/main.go

func init() {
	api.Register(white.NewIPWhitelist())
}

On ip_whitelist.go

func NewIPWhitelist(ips ...string) plugin.Plugin {
log.Print(ips, "Ips for plugin")

./micro api --ip_whitelist=10.1.1.10,10.1.1.11,10.1.2.0/24

_[]Ips for plugin_

_Registering RPC Handler at /rpc
Registering API Default Handler at /
handler
Listening_
