### ISSUE TITLE
gossip plugin instructions did not work

### ISSUE THREAD

**Issue by dikarel** [micro/go-plugins#63]
According to the [readme](https://github.com/micro/go-plugins/blob/master/registry/gossip/README.md), I only need to add this to my code to add gossip capability:

```go
import _ "github.com/micro/go-plugins/registry/gossip"
```

That did not work and only resulted in this:
![screen shot 2016-11-05 at 3 20 03 pm](https://cloud.githubusercontent.com/assets/15131271/20028707/a6546bfc-a36b-11e6-9ba1-0721354cea7f.png)

I had to do this instead to get it to work:

```go
import "github.com/micro/go-plugins/registry/gossip"

server.Init(
  ...,
  server.Registry(gossip.NewRegistry()),
)
```

Is it possible the readme instructions are outdated?

**Comment by asim** [comment]
You have to specify the flag `--registry=gossip`. I'll update the readme. If you've looked at any other documentation for go-micro you'll see that's a requirement.

**Comment by dikarel** [comment]
Sound good. Thanks for the quick response.
