### ISSUE TITLE
the MQTT broker plugin can't support encoding  broker.Message, how I can strip the encoding?

### ISSUE THREAD

**Issue by qudenger** [micro/go-plugins#68]
I use emqtt as my mqtt broker, and use the micro/go-plugin/broker/mqtt as the client on server, but the mqtt plugin implements the interface of micro broker, and I want strip the encoding of broker.Message, what should I do?

**Comment by asim** [comment]
Configurable encoders for the broker will be available in 1-2 weeks so you'll be able to define your own then but essentially the publish/subscribe will always require a broker.Message.

**Comment by qudenger** [comment]
Ok, Thank you for your quick reply and the great work!

**Comment by asim** [comment]
Configurable codecs were added with this PR https://github.com/micro/go-micro/pull/143 and this commit https://github.com/micro/go-plugins/commit/ecad760b6be398a4026ce0df6f2dd719b58ffedd

To use a codec you can basically pass it as an option when creating the broker.

```
import (
    "github.com/micro/broker"
    "github.com/micro/broker/codec/noop"
    "github.com/micro/go-plugins/broker/mqtt"
)

b := mqtt.NewBroker(
    broker.Codec(noop.NewCodec()),
)
```

For your requirement in not encoding/decoding a broker.Message you will want the `noop` codec as specified in the import and available at `github.com/micro/broker/codec/noop`. This codec will use the broker.Message Body and ignore the headers. When you Publish/Subscribe it will still require a broker.Message but will just use Body. 

If this is satisfactory please close the issue.

**Comment by qudenger** [comment]
It works and more expansible, you always gets things done efficiently. thank you again. @asim
