### ISSUE TITLE
use sarama kafka lib latest will occur "invalid configuration (Producer.Return.Successes must be true to be used in a SyncProducer)"

### ISSUE THREAD

**Issue by liutaihua** [micro/go-plugins#91]
kafka broker plugin use sarama sync producer client, but at latest version of sarama will occur error if there is not set  sarama.Config.Producer.Return.Successes as true.

I'm not sure is any other occur mistaken if i fix this sample like use  xxx.Config.Producer.Return.Successes  = true ?

and i have a doubt that why use Sync Producer instead of Async Producer?

**Comment by asim** [comment]
Fixed https://github.com/micro/go-plugins/commit/ac3c268737b591d4cd9cc8ecc8b9f92eac259438
