### ISSUE TITLE
NSQ broker does not support nsqlookupd

### ISSUE THREAD

**Issue by ginuerzh** [micro/go-plugins#92]
The nsq broker can only subscribe to nsqd address (e.g. 127.0.0.1:4150), but the nsqlookupd address (e.g. 127.0.0.1:4160/127.0.0.1:4161) does not work.

**Comment by asim** [comment]
NSQ Lookupd is not supported. I am unlikely to implement this change. Feel free to PR if you have something adequate.

**Comment by scholar-ink** [comment]
me too.Can't support Lookupd, it's very inconvenient in k8s

**Comment by asim** [comment]
The ability to specify lookupds was added. Please go see the nsq broker. https://github.com/micro/go-plugins/blob/master/broker/nsq/options.go#L54
