### ISSUE TITLE
can not set the exchange when using rabbitmq broker.

### ISSUE THREAD

**Issue by lcg635** [micro/go-plugins#94]
there is no options to set the exchange

**Comment by asim** [comment]
You can set the DefaultExchange https://github.com/micro/go-plugins/blob/master/broker/rabbitmq/connection.go#L18 but your right there's currently no option.

**Comment by asim** [comment]
Option added https://github.com/micro/go-plugins/commit/0b8224f7bcbf56ce0497f92be59d3b689560f3ee

**Comment by lcg635** [comment]
thank you asim!
