### ISSUE TITLE
How to set exchange option on rabbitmq broker

### ISSUE THREAD

**Issue by kitwalker12** [micro/go-plugins#95]
Hi,

I'm a bit new to go. I was wondering how would one go about setting the `exchangeKey` in `broker.Init()`

I understand the rabbitmq URL can be set in such a way 
```
broker.Init(broker.Option(func(o *broker.Options) {
    o.Addrs = []string{os.Getenv("RABBITMQ_URL")}
}))
```

not sure how the `exchangeKey` would be set.

Thanks

**Comment by asim** [comment]
Read Dave Cheney's blog post on options to get a better idea of how they work. https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis 

Do not create an anonymous function like that. An address option already exists. https://godoc.org/github.com/micro/go-micro/broker#Addrs

It's set like so

```
r := rabbitmq.NewBroker(micro.Addrs("foo"))
```

You can set the exchange in two ways. Either using the DefaultExchange global variable `rabbitmq.DefaultExchange = "foo"` or via an option https://godoc.org/github.com/micro/go-plugins/broker/rabbitmq#Exchange.

```
r := rabbitmq.NewBroker(
    rabbitmq.Exchange("foo"),
)
```

The rabbitmq broker creates a persistent connection when its created, passing options during Init will not do anything. Please create a new broker and pass options in.

Hope that helps.

**Comment by kitwalker12** [comment]
Thanks a lot @asim
