### ISSUE TITLE
A panic occur when unsubscribing from topic using kafka broker

### ISSUE THREAD

**Issue by lcg635** [micro/go-plugins#96]
2017/04/15 10:42:48 Unsubscribing from topic:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1544540]

goroutine 332 [running]:
github.com/micro/go-plugins/broker/kafka.(*kBroker).Subscribe.func1(0xc4204ca0c0, 0xc4201563f0, 0xc4207f1f80, 0xc4208f0330)
	/Users/lcg/code/wolf-backend/vendor/src/github.com/micro/go-plugins/broker/kafka/kafka.go:176 +0x310
created by github.com/micro/go-plugins/broker/kafka.(*kBroker).Subscribe
	/Users/lcg/code/wolf-backend/vendor/src/github.com/micro/go-plugins/broker/kafka/kafka.go:189 +0x234

the variable sm is nil

**Comment by asim** [comment]
Maybe submit a PR next time? It's a simple fix. https://github.com/micro/go-plugins/commit/737f4cf8c6cbb28af0b9bf2055317e2521a20e2b
