### ISSUE TITLE
rabbitmq consumer channel  can't reconnet when the tcp connection close

### ISSUE THREAD

**Issue by lcg635** [micro/go-plugins#97]
When I use rabbitmq broker, the ExchangeChannel can reconnect to rabbitmqserver if the tcp connection closed,  but there is no way to reconnect the ConsumeChannel

**Comment by asim** [comment]
There have been a number of requests for resubscribing. The reconnection logic is not simple. If you want to attempt to rework the broker I welcome a PR but it's unlikely I'll get to this any time soon.
